src/components/Icon/Icon.constants.ts
src/components/Icon/Icon.tsx
src/components/Icon/Icon.unit.test.tsx
src/components/Icon/Icon.unit.test.tsx.snap

The new svg Icon component forces the viewBox to be "0 0 32 32". For most icons this is fine. However some (like "info-badge-filled" and "error-legacy-badge-filled"), the viewPort in the svg is "0 0 14 14" . When this gets overwritten, the svg is now being drawn with the wrong viewPort, so it appears smaller than it should (14/32 of the size it should be for the two examples). This PR fixes that case.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-281641

feat(components/Icon): add-specific-case-for-viewbox-size

---

src/components/ListItemBase/ListItemBase.style.scss
src/components/SpaceListItem/SpaceListItem.style.scss
src/components/SpaceListItem/SpaceListItem.tsx
src/components/SpaceListItem/SpaceListItem.unit.test.tsx.snap
src/components/Text/Text.style.scss

Small css fixes for compact mode / size 32 of the SpaceListItem component.
It also includes font colour correction for default vs activity states.
I have also removed the colour on the Text component. This should inherit the default colour from the theme provider. It makes it hard to override if it has a specific class with colour assigned to it.

feat(sace-list-item): fix copact color

---

src/components/Popover/Popover.stories.args.ts
src/components/Popover/Popover.stories.docs.mdx
src/components/Popover/Popover.tsx
src/components/Popover/Popover.types.ts
src/components/Popover/Popover.unit.test.tsx
src/components/Popover/index.ts

The scope of the changes in this pull request are to amend the abstracted functional logic from `Tippy.js` for externally handling popovers from outside of the provided trigger component.
[SPARK-300653](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-300653)

feat(components/popover): add manual triggers

---

src/components/ButtonControl/ButtonControl.types.ts
src/components/ButtonSimple/ButtonSimple.stories.args.ts
src/components/ButtonSimple/ButtonSimple.tsx
src/components/ButtonSimple/ButtonSimple.types.ts
src/components/ButtonSimple/ButtonSimple.unit.test.tsx
src/components/Popover/Popover.stories.tsx
src/components/Popover/Popover.unit.test.tsx

Consuming the ButtonSimple (and its variants) within the Popover led to an issue where the click event was catched correctly as a trigger by the Popover, but tabbing and pressing enter on a ButtonSimple didn't cause a onClick event.
The problem is related to React-aria, where the onKeyDown event on a button results in a onPress and doesn't bubble up the onClick event as you would expect from a normal HTML button element. 
To fix this, we are going to override the onKeyDown coming from react-aria, if we need to (for example when using it on a Popover).
[React-aria issue](https://github.com/adobe/react-spectrum/issues/2100)

fix(components/button-simple): Not bubble up onClick

---

src/index.js

Overlay trigger was removed but the export wasn't.

feat(overlaytrigger): remove overlay trigger export

---

src/components/ListItemBase/ListItemBase.stories.args.ts
src/components/ListItemBase/ListItemBase.style.scss
src/components/Menu/Menu.stories.tsx
src/components/MenuTrigger/MenuTrigger.stories.tsx
src/components/Select/Select.stories.tsx

Small PR to fix text-overflow in list-item base.
Also updated some docs around select, menu, menu trigger.
Usage in Select

feat(list-item-base): fix overflow, add some examples in docs

---

package.json
src/components/Avatar/Avatar.style.scss
src/components/ButtonCircle/ButtonCircle.style.scss
src/components/ButtonPill/ButtonPill.style.scss
src/components/Overlay/Overlay.style.scss
src/components/ThemeProvider/ThemeProvider.style.scss
yarn.lock

PR to add the variant of outline circle and pill buttons with non-ghost or solid background, as specified here:
[*Figma link*](https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web?node-id=6361%3A0)
* New components tokens were created for this with the prefix --videoSupport. The reason why the name is like that is because this component is located in page Realtime > Video support in the Figma library, for now. We have requested Momentum team to move these solid buttons to the buttons sections to keep consistency. They have it on their backlog. To keep consistency with Momentum as it is right now, the component token was named with the actual component location in mind (--videoSupport). When the Momentum team updates this, we will update the token and MRV2 as well.
* Button …

feat(component-variant/solid-button-2): adding styles for circle and pill solid outline button

---

scss/components/link/module.scss

trying to convert from node-sass to sass encountered this error. missing semi-colon

fix(sass): missing semicolon

---

package.json
yarn.lock

I noticed our package.json has `react-redux`. This project doesn't use `react-redux` so this PR removes it.

chore(deps): remove unused library

---

src/components/Banner/Banner.unit.test.tsx.snap
src/components/ButtonCircle/ButtonCircle.style.scss
src/components/ButtonGroup/ButtonGroup.constants.ts
src/components/ButtonGroup/ButtonGroup.stories.args.ts
src/components/ButtonGroup/ButtonGroup.stories.tsx
src/components/ButtonGroup/ButtonGroup.style.scss
src/components/ButtonGroup/ButtonGroup.tsx
src/components/ButtonGroup/ButtonGroup.types.ts
src/components/ButtonGroup/ButtonGroup.unit.test.tsx.snap
src/components/ButtonPill/ButtonPill.style.scss
src/components/Coachmark/Coachmark.unit.test.tsx.snap
src/components/MeetingListItem/MeetingListItem.unit.test.tsx.snap
src/components/ReactionPicker/ReactionPicker.unit.test.tsx.snap
src/components/Toast/Toast.unit.test.tsx.snap
src/components/ToastContent/ToastContent.unit.test.tsx.snap

Updates were made to the ButtonGroup component to make it easier to use it with the audio/video controls design.
* Added a "compressed" property to compress horizontal space and remove inner borders around ChildNodes
* Added new Compressed and Audio Video Controls stories.
* Updated snaps of components that used ButtonGroup since it added data-compressed={false} to all of them.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-303422

task(components/button-group): button-group update to ease use in audio/video controls

---

src/components/ButtonGroup/ButtonGroup.stories.tsx
src/components/ButtonGroup/ButtonGroup.style.scss

*Provide a general summary of the scope of the changes in this pull request.*
Fix the left and right borders of ButtonGroup when a non-button is included in the children (e.g. MenuTrigger).
(second attempt because first ran into rebase problems)
Added a MenuTrigger to the Audio Video Controls story as a test. Updated the .scss to select button last/first-of-type when adding begin/end border and border-radius.

fix(components/button-group): fix right border if MenuTrigger is child

---

src/components/Icon/Icon.constants.ts
src/components/SpaceListItem/SpaceListItem.stories.args.ts
src/components/SpaceListItem/SpaceListItem.tsx
src/components/SpaceListItem/SpaceListItem.types.ts
src/components/SpaceListItem/SpaceListItem.unit.test.tsx
src/components/SpaceListItem/SpaceListItem.unit.test.tsx.snap

feat(components/SpaceListItem): add-draft-message-icon-indicator-inside-space-list

---

src/components/MenuTrigger/MenuTrigger.stories.docs.mdx
src/components/MenuTrigger/MenuTrigger.tsx
src/components/MenuTrigger/MenuTrigger.types.ts
src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/components/Popover/Popover.tsx
src/components/Popover/Popover.types.ts

- the internal state of the menuTrigger doesn't reflect correctly when popover was closed via click outside
- warnings about type of children in MenuTrigger, removed
- children type for MenuTrigger is `ReactElement[]` which is wrong, it's supposed to be `ReactNode`. 
- updated docs for MenuTrigger

feat(menu-trigger): bug fixes

---

src/components/Icon/Icon.constants.ts
src/components/Icon/Icon.tsx
src/components/Icon/Icon.types.ts
src/components/Icon/Icon.unit.test.tsx
src/components/Icon/Icon.unit.test.tsx.snap
src/components/SpaceListItem/SpaceListItem.tsx
src/components/SpaceListItem/SpaceListItem.types.ts

Currently we do not provide users with tooltip information regarding space list icons on Web. Tooltips are needed for most icons as it is not obvious to the user what they are. This was highlighted after the introduction of the draft indicator.
**OLD IMPLEMENTATION (without tooltip)** 
**NEW IMPLEMENTATION (with tooltip)**
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-323707
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-323825
https://www.figma.com/file/IyTViwqLFPjlbmX84QeQd8/SPARK-320154%3A-Tooltips-for-space-list-icons?node-id=2%3A3)
PR on web-webex-client
https://sqbu-github.cisco.com/WebExSquared/webex-web-client/pull/2594

feat(icons): tooltips for space list icons

---

src/components/ReactionBadge/ReactionBadge.style.scss

Small CSS fix for reaction count's vertical alignment. [As per the figma](https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=5585%3A13026) the height for the div/span should've been 16px/1rem
Left: with CSS fix | Right: current view
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-224533
https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=5585%3A13026

fix(reaction): css fix for reaction count alignment

---

config/typescript/tsconfig.cjs.json
config/typescript/tsconfig.esm.json
jest.config.js
src/components/Icon/Icon.unit.test.tsx
src/hooks/useDynamicJSONImport.test.ts
src/hooks/useDynamicJSONImport.ts
src/hooks/useDynamicSVGImport.test.ts
src/hooks/useDynamicSVGImport.ts
tools/reactionMock.js
tsconfig.json

Update the module for both cjs and esm to es2020. This is necessary for SVGs to be dynamically loaded.
The reaction animations work the same way so I also fixed those as well.
A way to test this is working on the storybook is to pop out the Icon story page as a separate window. Open the network tab and refresh the page. There should be a separate request for the icon chunk (it will be a js bundle)
This will break downstream projects that require less than es2020 support. They should push momentum through babel if that support is required.

Fix svgr dynamic loading

---

src/components/MenuTrigger/MenuTrigger.tsx
src/components/MenuTrigger/MenuTrigger.unit.test.tsx
src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/components/Popover/Popover.constants.ts
src/components/Popover/Popover.tsx
src/components/Popover/Popover.types.ts
src/components/Popover/Popover.unit.test.tsx
src/components/Popover/tippyPlugins.test.ts
src/components/Popover/tippyPlugins.ts

- Added a plugin to Popover to fix the hideOnEsc (hideOnEsc is turned on by default)
- Added unit tests for it
- Set hideOnEsc to false in MenuTrigger component (Escape is handled separately there).
Side Note: noticed Bug in MenuTrigger, which could be fixed with this new hideOnEsc Popover functionality:
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-342208
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-342004

fix: added hideOnEsc on Popover

---

src/components/Card/Card.tsx
src/components/Tag/Tag.constants.ts
src/components/Tag/Tag.stories.tsx
src/components/Tag/Tag.style.scss
src/components/Tag/Tag.tsx
src/components/Tag/Tag.types.ts
src/components/Tag/Tag.unit.test.tsx

When a tag is "pressable" (used as a button), the cursor should be set to the pointer (to match our other buttons).
* Updated Tag component to add an 'md-tag-pressable' css class that has a 'cursor: pointer' style.
* Added tests for pressable/not-pressable, etc
* Added the missing isDisabled type
* removed an unused line of code in Card.tsx (unrelated to this change)
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-336426

fix(tag): pointer cursor on pressable tag

---

src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/components/Popover/Popover.constants.ts
src/components/Popover/Popover.stories.args.ts
src/components/Popover/Popover.stories.tsx
src/components/Popover/Popover.style.scss
src/components/Popover/Popover.tsx
src/components/Popover/Popover.types.ts
src/components/Popover/Popover.unit.test.tsx
src/components/Popover/Popover.unit.test.tsx.snap

- Added `closeButtonPlacement` to configure the popover to have a close button (`top-left' | 'top-right' | 'none'`)
- Added `focusBackOnTrigger` to configure the popover to focus back on trigger on close
- Added `closeButtonProps` to support the `closeButtonPlacement` and give flexibility to add accessibility props on the close button (aria label, title, translation etc)

feat(popover): add close btn and focusBackOnTrigger

---

src/components/Icon/Icon.constants.ts

Add `warning-badge` as small icon exception.
There's a small issue with the icon itself, it was designed at 16x16 instead of 14x14 like the rest of the exception icons.
[I've left a comment in the figma](https://www.figma.com/file/SXK8Gb5tMlN9xiG2cC4OBu?node-id=9091:12274#230785156) -- this will probabbly automatically get fixed when they fix it on their end.

feat(icons): add warning-badge as exception

---

src/components/Popover/Popover.style.scss
src/components/Popover/Popover.tsx

Cheeky little flex-shrink to avoid random resizing of the icon inside the close button. It currently doesn't look good in Cantina because we have this snippet in the _base.scss 
```
* {
min-width: 0;
min-width: 0;
}
```
This will make sure the icon will always look ok.

Feat/popover/add add flex-shrink:0 to svg in close button

---

src/legacy/List/index.js
src/legacy/Menu/index.js

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-343215
Fix several instances of focus being used potentially on a null result of a query. These have been known to cause crashes
No tests because these are in a legacy component.

fix(list): fix focus crashes

---

src/examples/data/components.js
src/index.js
src/legacy/Checkbox/examples/Default.js
src/legacy/Checkbox/examples/Disabled.js
src/legacy/Checkbox/examples/Group.js
src/legacy/Checkbox/examples/Indeterminate.js
src/legacy/Checkbox/examples/KitchenSink.js
src/legacy/Checkbox/examples/KitchenSink.stories.tsx
src/legacy/Checkbox/examples/Nested.js
src/legacy/Checkbox/examples/index.js
src/legacy/Checkbox/index.js
src/legacy/Checkbox/tests/index.cy.js
src/legacy/Checkbox/tests/index.spec.js
src/legacy/Checkbox/tests/index.spec.js.snap
src/legacy/CheckboxGroup/index.js
src/legacy/CheckboxGroup/tests/index.spec.js
src/legacy/CheckboxGroup/tests/index.spec.js.snap
src/legacy/InputHelper/examples/Default.js
src/legacy/InputHelper/examples/KitchenSink.js
src/legacy/InputHelper/examples/KitchenSink.stories.tsx
src/legacy/InputHelper/examples/index.js
src/legacy/InputHelper/index.js
src/legacy/InputHelper/tests/index.cy.js
src/legacy/InputHelper/tests/index.spec.js
src/legacy/InputHelper/tests/index.spec.js.snap
src/legacy/List/examples/ListWithEventBubbling.js
src/legacy/SelectOption/index.js
src/legacy/SelectOption/tests/index.spec.js
src/legacy/index.js

Reverts momentum-design/momentum-react-v2#281
PR 281 removed InputHelper, but Input was actually still using it

Revert "Remove legacy checkbox"

---

src/legacy/Menu/examples/CustomMenuItems.js
src/legacy/MenuItem/index.js
src/legacy/MenuItem/tests/index.spec.js

Legacy Menu Items were preventDefaulting events when a toggle is provided as children causing keyboard accessibility on the toggle to break. This PR makes sure the events for menu-item are only handled when the event target is the menu-item itself.

feat(menu-item): fix toggle accessibility issue

---

src/components/Tab/Tab.style.scss

Literally removing two characters changing the color var name from "inactive" into "active".
[SPARK-332386](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-332386) Tab active state colour is incorrect

fix: remove the two characters from line 34

---

src/components/MenuTrigger/MenuTrigger.style.scss
src/components/Tab/Tab.style.scss

defines the width of the separator as being 100% of its parent element (it was 0 before)
[SPARK-332388](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-332388)
Separator for MenuTrigger with multiple menus doesn't get displayed

Fix: MenuTrigger separator width 

---

package.json
src/components/ButtonCircleToggle/ButtonCircleToggle.constants.ts
src/components/ButtonCircleToggle/ButtonCircleToggle.stories.args.ts
src/components/ButtonCircleToggle/ButtonCircleToggle.stories.docs.mdx
src/components/ButtonCircleToggle/ButtonCircleToggle.stories.tsx
src/components/ButtonCircleToggle/ButtonCircleToggle.style.scss
src/components/ButtonCircleToggle/ButtonCircleToggle.tsx
src/components/ButtonCircleToggle/ButtonCircleToggle.types.ts
src/components/ButtonCircleToggle/ButtonCircleToggle.unit.test.tsx
src/components/ButtonCircleToggle/ButtonCircleToggle.unit.test.tsx.snap
src/components/ButtonCircleToggle/index.ts
src/components/index.ts
src/index.js
src/storybook/helper.stories.argtypes.ts
yarn.lock

PR to implement the buttonCircleToggle component. This is a component that is based on ButtonCircle and adds toggle hooks to it to make it toggable/selectable. 
As for now, only the outline and ghost buttons have a toggable version designed in the component library, which only cover these button colour types in the scope.
[*Links to relevent resources.*](https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web?node-id=4445%3A5884)

feat(toggle-circle-button): implement button circle toggle

---

src/components/ButtonCircleToggle/ButtonCircleToggle.stories.tsx
src/components/ButtonCircleToggle/ButtonCircleToggle.tsx
src/components/ButtonCircleToggle/ButtonCircleToggle.unit.test.tsx.snap

React Aria's useToggleButton hook was engineered to be used in an html button, meaning it is providing the callback action via the onClick property to the button. We are using this hook in our existent ButtonCircle, which expects onPress as the callback method, not onClick. 
Also, properties passed to ButtonCircleToggle were not passed to ButtonCircle, like the properties to use a Popover triggered by this toggle. 
This PR intends to fix these two things in ButtonCircleToggle.

feat(button-circle-toggle-props): fix onChange prop

---

src/components/Tab/Tab.style.scss

I had forgotten to do the same modifications to a line below as well.
Does what should have been done from this PR:
https://github.com/momentum-design/momentum-react-v2/commit/7578ceb5918f6fd644f919acdda7d87bb46a63a3
[SPARK-332386](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-332386) Tab active state colour is incorrect

fix: another two characters that should be deleted 'inactive'->'active'

---

src/components/ButtonCircleToggle/ButtonCircleToggle.tsx
src/components/ButtonCircleToggle/ButtonCircleToggle.unit.test.tsx.snap
src/components/ButtonPill/ButtonPill.style.scss
src/components/ButtonPillToggle/ButtonPillToggle.constants.ts
src/components/ButtonPillToggle/ButtonPillToggle.stories.args.ts
src/components/ButtonPillToggle/ButtonPillToggle.stories.docs.mdx
src/components/ButtonPillToggle/ButtonPillToggle.stories.tsx
src/components/ButtonPillToggle/ButtonPillToggle.style.scss
src/components/ButtonPillToggle/ButtonPillToggle.tsx
src/components/ButtonPillToggle/ButtonPillToggle.types.ts
src/components/ButtonPillToggle/ButtonPillToggle.unit.test.tsx
src/components/ButtonPillToggle/ButtonPillToggle.unit.test.tsx.snap
src/components/ButtonPillToggle/index.ts
src/components/index.ts
src/index.js

PR to implement the buttonPillToggle component. This is a component that is based on ButtonPill and adds toggle hooks to it to make it toggable/selectable. 
As for now, only the outline and ghost buttons have a toggable version designed in the component library, which only cover these button colour types in the scope.
[*Links to relevent resources.*](https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web?node-id=4445%3A5884)

feat(button-pill-toggle): implement button pill toggle

---

src/components/TextInput/TextInput.stories.tsx
src/components/TextInput/TextInput.style.scss

This PR styles the autofill icon in Safari so that it is visible in our dark theming - the same changes as made in https://sqbu-github.cisco.com/WebExSquared/webex-web-client/pull/3032 but generalising them to the momentum component. It also removes the yellow autofill box on Safari (except in the case of a suggested password) and Firefox, making it transparent. In the case of a suggested password in Safari the yellow box is restyled to have a border radius which aligns with that of the TextInput.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-362673
Safari ->
Before
After 
Firefox -> 
Before
After

fix(autofill-colours): remove yellow autofill box and styling fixes

---

src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/components/Popover/Popover.tsx

Added a padding of 8 as the default to ensure popovers are never touching the window (currently they do, with the padding they will not).
https://popper.js.org/docs/v2/modifiers/prevent-overflow/#padding

fix: added padding to preventOverflow

---

src/components/SpaceListItem/SpaceListItem.constants.ts
src/components/SpaceListItem/SpaceListItem.tsx
src/components/SpaceListItem/SpaceListItem.unit.test.tsx
src/components/SpaceListItem/SpaceListItem.utils.test.tsx
src/components/SpaceListItem/SpaceListItem.utils.ts

This PR covers the case where secondLine can be passed as null as a prop. I separated out some of the logic to a utils file and wrote a test to cover edge cases.

fix(space-list-item): cover null case for second-line

---

src/components/SearchInput/SearchInput.constants.ts
src/components/SearchInput/SearchInput.stories.args.ts
src/components/SearchInput/SearchInput.stories.docs.mdx
src/components/SearchInput/SearchInput.stories.tsx
src/components/SearchInput/SearchInput.style.scss
src/components/SearchInput/SearchInput.tsx
src/components/SearchInput/SearchInput.types.ts
src/components/SearchInput/SearchInput.unit.test.tsx
src/components/SearchInput/SearchInput.unit.test.tsx.snap

This PR fixes some of the styling in the SearchInput component:
- Changes weight of icons to "bold"
- Centres the icons and text within the wrapper div 
- Moves the icons closer to the sides of the wrapper
- Adds the two height variations as seen in the Figma and adds a default width
- Replaces the old 'searching' icon with the LoadingSpinner component
I had a look at why the 'searching' icon doesn't seem to work and it's to do with how it's being used in Cantina - the boolean 'searching' prop isn't being used and so the component never changes the icons.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-356975
https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web?node-id=25054%3A38561
Before: 
After:

fix(search-input): fix styling to align with figma

---

src/components/Avatar/Avatar.constants.ts
src/components/Avatar/Avatar.stories.args.tsx
src/components/Avatar/Avatar.stories.tsx
src/components/Avatar/Avatar.style.scss
src/components/Avatar/Avatar.tsx
src/components/Avatar/Avatar.types.ts
src/components/Avatar/Avatar.unit.test.tsx
src/components/Avatar/Avatar.unit.test.tsx.snap
src/components/AvatarMeetingsListItem/AvatarMeetingsListItem.unit.test.tsx.snap

This PR aligns the avatar component more with what appears on the Figma:
- Add avatar size 64
- Change shape of presence icon wrapper depending on presence used
- Moved story argTypes to a separate file
- Removed unnecessary args from each story in storybook
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-367923
https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web?node-id=41210%3A65884
Before: 
After:

fix(avatar): add size 64 and change shape of presence icon 

---

src/components/List/List.unit.test.tsx
src/components/ListItemBase/ListItemBase.tsx
src/components/ListItemBase/ListItemBase.utils.test.tsx
src/components/ListItemBase/ListItemBase.utils.tsx
src/hooks/useMutationObservable.test.tsx
src/hooks/useMutationObservable.ts

Use MutationObserver to detect when any focusable item changed in list item subtree. It is necessary to set the tabindex to -1 of all focusable elements which are in non-selected row.
issue: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-376372

fix: handle dynamic changes in the list base item subtree

---

src/components/OverlayAlert/OverlayAlert.types.ts

The scope of the changes in this pull request are to add the missing props extension to the types file within `<OverlayAlert />` so that it properly extends the props from `<Overlay />`.

fix(overlay-alert): extend overlay props

---

src/components/Icon/Icon.style.scss

Adding `flex-shrink` property to Icon to avoid it shrinking. Without it, it naturally wants to shrink because the icon has a `display:flex` property (to make it center-aligned)

feat(icon-shrink): add flex-shrink 0 to icon

---

src/components/MenuTrigger/MenuTrigger.tsx

[SPARK-383510](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-383510): MenuTrigger component opens again when double clicking for 1st time. 
Every time you open Menu Trigger for the first time, or after clicking away of it:
1 Click --> Opens menu (correct)
2 Click --> Opens menu again! (bug)
3 Click --> Closes menu  (correct)
4 Click --> Opens menu (correct)
5 Click --> Closes menu  (correct)
6 Click --> Opens menu (correct)
7 Click --> Closes menu  (correct)
8 Click --> Opens menu (correct)

feat(menu-trigger-fix): fix double click bug on menuTrigger component

---

src/components/ModalContainer/index.ts
src/components/Overlay/index.ts
src/components/OverlayAlert/OverlayAlert.stories.args.ts
src/components/OverlayAlert/OverlayAlert.style.scss
src/components/OverlayAlert/OverlayAlert.tsx
src/components/OverlayAlert/OverlayAlert.types.ts
src/components/OverlayAlert/OverlayAlert.unit.test.tsx
src/components/OverlayAlert/OverlayAlert.unit.test.tsx.snap
src/components/ThemeProvider/ThemeProvider.style.scss

The scope of the changes in this pull request are to add support for the lack of a `title` prop to `<OverlayAlert />` and to add color props to the existing `<OverlayAlert />` component that bubble into `<ModalContainer />` and `<Overlay />` respectively. This also is inclusive of a small fix around border style globals and exports of additional types.

Fix/overlay alert/support no title

---

src/components/ButtonGroup/ButtonGroup.tsx
src/components/ButtonGroup/ButtonGroup.types.ts
src/components/ButtonGroup/ButtonGroup.unit.test.tsx
src/components/ButtonGroup/ButtonGroup.unit.test.tsx.snap
src/components/ButtonSimple/ButtonSimple.tsx
src/components/ButtonSimple/ButtonSimple.types.ts
src/components/ButtonSimple/ButtonSimple.unit.test.tsx
src/components/ButtonSimple/ButtonSimple.unit.test.tsx.snap

PR to add role prop for ButtonGroup and ButtonSimple components for accessibility fixes related to [Jira](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-367395). 
Right now the tablist and tab roles are not getting reflected due to which screen readers cannot correctly work on the Space List Header buttons (All, Direct and Spaces).

fix(buttongroup): added role prop for accessibility

---

scss/components/input/input.scss

It looks like a recent change to momentum (looks like https://github.com/momentum-design/momentum-react-v2/pull/339/) has left the hover color with an unset variable (--mds-color-theme-background-solid-primary-normal-hovered). This means that in dark mode it falls back to the light theme color.
[SPARK-393277](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-393277)

SPARK-393277: Input hover color broken

---

src/components/ButtonPill/ButtonPill.style.scss

According to lates figma, the text size of a 28px button is 14px (https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web-Application?node-id=4445%3A3906&t=BXY8iy3MUECRJwI1-1). 14px = 0.875rem

feat(button-pill-size): update text color of 28px pill button

---

src/components/Banner/Banner.unit.test.tsx.snap
src/components/ButtonGroup/ButtonGroup.constants.ts
src/components/ButtonGroup/ButtonGroup.stories.args.ts
src/components/ButtonGroup/ButtonGroup.stories.tsx
src/components/ButtonGroup/ButtonGroup.style.scss
src/components/ButtonGroup/ButtonGroup.tsx
src/components/ButtonGroup/ButtonGroup.types.ts
src/components/ButtonGroup/ButtonGroup.unit.test.tsx
src/components/ButtonGroup/ButtonGroup.unit.test.tsx.snap
src/components/Coachmark/Coachmark.unit.test.tsx.snap
src/components/MeetingContainer/MeetingContainer.unit.test.tsx.snap
src/components/MeetingListItem/MeetingListItem.unit.test.tsx.snap
src/components/ReactionPicker/ReactionPicker.unit.test.tsx.snap
src/components/Toast/Toast.unit.test.tsx.snap
src/components/ToastContent/ToastContent.unit.test.tsx.snap

For in-meeting reactions, we need a button group that has a small separator in the middle. I added a separator property to our Button Group to enable/disable this ui element in the component. 
Spec
Storybook
[SPARK-399325](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-399325)

SPARK-399325: add separator line in button group

---

src/components/ButtonHyperlink/ButtonHyperlink.constants.ts
src/components/ButtonHyperlink/ButtonHyperlink.stories.args.ts
src/components/ButtonHyperlink/ButtonHyperlink.stories.tsx
src/components/ButtonHyperlink/ButtonHyperlink.style.scss
src/components/ButtonHyperlink/ButtonHyperlink.tsx
src/components/ButtonHyperlink/ButtonHyperlink.types.ts
src/components/ButtonHyperlink/ButtonHyperlink.unit.test.tsx
src/components/ButtonHyperlink/ButtonHyperlink.unit.test.tsx.snap
src/components/MeetingContainer/MeetingContainer.unit.test.tsx.snap

Adding inverted property to hyperlink to be able to get a hyperlink that works with an opposite-theme background, as added to the [Component Figma Library](https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web-Application?node-id=4649%3A91&t=hecg0EMC6gzAraod-1). 
That is to achieve inverted elements like in this spec:

feat(inverted-hyperlink): add inverted prop to hyperlink

---

src/components/List/List.unit.test.tsx
src/components/ListItemBase/ListItemBase.constants.ts
src/components/ListItemBase/ListItemBase.tsx
src/components/ListItemBase/ListItemBase.unit.test.tsx
src/components/ListItemBase/ListItemBase.utils.test.tsx
src/components/ListItemBase/ListItemBase.utils.tsx

Change keyboard navigation of ListItems with interactive children to use left/right arrow keys. Since there's no guidelines on interactive elements within interactive list items (discouraged actually) other similar structures have been used for reference, such as Grid.
As per new accessibility requirements, if a list item has interactive children then pressing left/right arrow keys should be how they are navigated, instead of the current behavior which utilizes tab. Up/down arrow keys will still navigate from one list item to other, including when pressed on a child element within a list item. Pressing tab/shift+tab on a list item will move the focus out to the list item, further tab/shift+tab on a list item will move focus out of the list, and when navigating back to the list then the …

feat(listitem): navigation with child elements

---

src/components/NotificationSystem/NotificationSystem.stories.tsx
src/components/NotificationSystem/NotificationSystem.tsx
src/components/NotificationSystem/NotificationSystem.types.ts
src/components/NotificationSystem/NotificationSystem.unit.test.tsx
src/components/NotificationSystem/NotificationSystem.unit.test.tsx.snap

chore(component/NotificationSystem): adding limit to toast notifs

---

src/components/OverlayAlert/OverlayAlert.constants.ts
src/components/OverlayAlert/OverlayAlert.stories.args.ts
src/components/OverlayAlert/OverlayAlert.tsx
src/components/OverlayAlert/OverlayAlert.unit.test.tsx
src/components/OverlayAlert/OverlayAlert.unit.test.tsx.snap

The scope of the changes in this pull request is to update `<OverlayAlert />` to have a default `<Overlay />` color of `secondary` for the more common use case within consuming applications with this component.

refactor(overlay-alert): default overlay color

---

package.json
src/components/Coachmark/Coachmark.unit.test.tsx
src/components/Coachmark/Coachmark.unit.test.tsx.snap
src/components/MenuTrigger/MenuTrigger.unit.test.tsx
src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/components/ModalContainer/ModalContainer.tsx
src/components/ModalContainer/ModalContainer.types.ts
src/components/ModalContainer/ModalContainer.unit.test.tsx
src/components/ModalContainer/ModalContainer.unit.test.tsx.snap
src/components/Popover/Popover.tsx
src/components/Popover/Popover.unit.test.tsx
src/components/Popover/Popover.unit.test.tsx.snap
yarn.lock

Arrow of reaction picker popover jumps up on reaction hover (after 5 secs). The popover has Reactions that, on hover, trigger another small popover with the label. The bug happens because there is a re-render after 5 seconds of user-inactivity, which causes the popovers's arrows to recalculate and update their style. MRV2's Popover used to give the same static id to its arrow, meaning that if there were 2 popovers open at the same time (like in the case of hovering over a reaction inside the ReactionPicker), the the style update was applied to both arrows. 
This PR intends to give a unique uuid (`uuid.v4()`) to each Popover instance arrow, so that this bug doesn't occur again.  
Before
After

feat(SPARK-406215): Fix lack of unique arrow id for popover

---

src/components/AriaToolbar/AriaToolbar.tsx
src/components/AriaToolbar/AriaToolbar.unit.test.tsx
src/components/AriaToolbar/AriaToolbar.unit.test.tsx.snap
src/components/Popover/Popover.stories.tsx
src/components/Popover/Popover.tsx
src/components/Popover/Popover.types.ts
src/components/Popover/Popover.unit.test.tsx

This allows specifying the element that a popover should focus on render using a function ref. See storybook for how this works.
Also in this PR are modifications to the AriaToolbar to
1) not render elements like null
2) handle being focused from outside

Popover first focus

---

package.json
yarn.lock

- Bumped momentum-design icons to latest version, since there were issues with `phone-filled` showing too small

fix(icons): bump md icons to latest

---

src/components/List/List.stories.args.ts
src/components/List/List.tsx
src/components/List/List.types.ts
src/components/List/List.unit.test.tsx
src/components/List/List.utils.tsx

Introduce a noLoop option for lists to opt out of the behavior of jumping to the other end of the list when you reach it by keyboard navigation. This will be used in lists where this is not going to work e.g. virtualized lists.

List no loop

---

src/components/Popover/Popover.unit.test.tsx

The test fails occasionally. I suspect when the test runs slowly, the popover has already closed by the time it checks so the original method used complains.

fix(popover): fix popover test

---

src/components/Select/Select.tsx
src/components/Select/Select.unit.test.tsx.snap

When a Select opens upwards (direct = up), the arrow shouldn't swap position. 
Universally, arrow-down means the Select is closed and arrow-up means the Select is open. Disregards the direction of the dropdown. 
Check Gmail for example:
Close dropdown = arrow down
Open dropdown = arrow up

feat(select-arrow-fix): fix direction of arrow

---

src/components/AlertBanner/AlertBanner.style.scss

fix/AlertBanner/change grow from 100% to auto to respect margin

---

src/components/AddReactionButton/AddReactionButton.unit.test.tsx.snap
src/components/AvatarMeetingsListItem/AvatarMeetingsListItem.unit.test.tsx.snap
src/components/Banner/Banner.unit.test.tsx.snap
src/components/ButtonCircle/ButtonCircle.constants.ts
src/components/ButtonCircle/ButtonCircle.stories.args.ts
src/components/ButtonCircle/ButtonCircle.stories.tsx
src/components/ButtonCircle/ButtonCircle.style.scss
src/components/ButtonCircle/ButtonCircle.tsx
src/components/ButtonCircle/ButtonCircle.types.ts
src/components/ButtonCircle/ButtonCircle.unit.test.tsx
src/components/ButtonCircle/ButtonCircle.unit.test.tsx.snap
src/components/ButtonCircleToggle/ButtonCircleToggle.unit.test.tsx.snap
src/components/ButtonGroup/ButtonGroup.stories.tsx
src/components/ButtonGroup/ButtonGroup.unit.test.tsx.snap
src/components/MeetingContainer/MeetingContainer.unit.test.tsx.snap
src/components/NotificationSystem/NotificationSystem.unit.test.tsx.snap
src/components/Popover/Popover.unit.test.tsx.snap
src/components/ReactionButton/ReactionButton.unit.test.tsx.snap
src/components/ReactionPicker/ReactionPicker.unit.test.tsx.snap
src/components/Toast/Toast.unit.test.tsx.snap

This PR adds the ```solid``` prop to ButtonCircle for use in pagination buttons. The ```solid``` prop cannot be used along with the ```color``` or ```ghost``` prop.
|ButtonCircle|ButtonGroup|
|---|---|
|![Screenshot 2023-05-25 at 21 22 57](https://github.com/momentum-design/momentum-react-v2/assets/86778628/027c8f98-3111-4d9f-b3fc-dfe9662cefb9)|![Screenshot 2023-05-25 at 21 22 47](https://github.com/momentum-design/momentum-react-v2/assets/86778628/66a9f823-5444-4180-9f3e-1255cd43b5ff)|

feat(ButtonCircle): add solid prop

---

src/components/Slider/Slider.hooks.ts
src/components/index.ts
src/index.js

- Fixes the exports of Slider component
- Had to revert the value handling of the useSlider hook, since it didn't work in Cantina

fix: slider exports and value handling

---

css/momentum-ui.css
scss/components/content-item/content-item.scss

Activity-item-fix-2: fix right margin and icon chip background color

---

src/components/ButtonCircle/ButtonCircle.style.scss

feat(fix-circle-button-disabled): fix background color

---

src/components/Overlay/Overlay.stories.tsx
src/components/Overlay/Overlay.tsx
src/components/Overlay/Overlay.types.ts
src/components/Overlay/Overlay.unit.test.tsx
src/components/Overlay/Overlay.unit.test.tsx.snap
src/components/OverlayAlert/OverlayAlert.constants.ts
src/components/OverlayAlert/OverlayAlert.tsx
src/components/OverlayAlert/OverlayAlert.types.ts
src/components/OverlayAlert/OverlayAlert.unit.test.tsx
src/components/OverlayAlert/OverlayAlert.unit.test.tsx.snap

- Added focusLockProps to Overlay. If present, the overlay will render inside a FocusLock
- Used these focusLockProps for OverlayAlert. OverlayAlert can still be configured to use different focusLockProps but the default is to returnFocus
Why didn't I just put the FocusLock in OverlayAlert? Because, like with legacy overlay component, overlays naturally want to restrict the focus to what they show in front of them and not behind them. I left this configurable in case there are exceptions to that.

feat(overlay-alert): focus lock

---

src/components/OverlayAlert/OverlayAlert.stories.tsx
src/components/OverlayAlert/OverlayAlert.style.scss
src/components/OverlayAlert/OverlayAlert.tsx
src/components/OverlayAlert/OverlayAlert.unit.test.tsx
src/components/OverlayAlert/OverlayAlert.unit.test.tsx.snap

Update the overlay alert to be in line with the latest UX figma
Before
After
Figma Design
Figma storybook example

fix(overlay-alert): fix spacing and corners of overlay alert

---

src/components/Popover/Popover.stories.tsx
src/components/Popover/Popover.tsx
src/components/Popover/Popover.unit.test.tsx
src/utils/applyRef.ts
src/utils/applyRef.unit.test.ts
src/utils/index.ts

Allow the `Popover` component to forward refs provided to it to the trigger component, via the tippy react component. This allows for `Popover`s to be used as trigger components themselves, which allows for multiple popovers to be applied to a single trigger. 
This enables consumers to add popovers with different triggers on them without needing to wrap the popover in a span / div / etc. A common use case for this is where a button needs to have a tooltip displayed on hover, but also to display some interactive content on click. A storybook example has been added for this common use case.

feat: popover forward ref

---

src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/components/Popover/LazyTippy.tsx
src/components/Popover/Popover.tsx
src/components/Select/Select.unit.test.tsx.snap

This change improves tippy instance handling (specifically via the `setInstance` prop) of popovers so that it no longer relies on accessing a DOM node in order to retrieve the current tippy instance. This means that nested popovers now (correctly) get their own instance, and much of the popover internals are simplified with regards to refs.
Note that I haven't yet added any tests for this. Since this is not a new behaviour (rather a refactor of an old one), I expect the existing set of tests should cover the changes. I am, of course, happy to add tests if wanted.
This change also makes the `applyRef` utility function unused, however I have left this in as it may have use in future. Again if this should be removed I am happy to do so.

feat: better handling of tippy instances

---

src/components/Overlay/Overlay.tsx
src/components/Overlay/Overlay.types.ts
src/components/OverlayAlert/OverlayAlert.stories.tsx
src/components/OverlayAlert/OverlayAlert.tsx
src/components/OverlayAlert/OverlayAlert.types.ts
src/components/OverlayAlert/OverlayAlert.unit.test.tsx
src/components/OverlayAlert/OverlayAlert.unit.test.tsx.snap

- Change the Overlayalert to allow for a onClose prop, which will be fired when Escape is pressed
- Allow the Overlay component to pass through `...other` props
- Added unit tests

fix: overlayalert to pass in onClose and escape

---

src/components/Select/Select.stories.args.ts
src/components/Select/Select.stories.tsx
src/components/Select/Select.style.scss
src/components/Select/Select.tsx
src/components/Select/Select.types.ts
src/components/Select/Select.unit.test.tsx
src/components/Select/Select.unit.test.tsx.snap

- Added `listboxWidth` prop to select to allow for popover `strategy: fixed`. This will fix a bug where when the select gets used in a scroll box, it can't break out of the scroll box.

feat: added listboxWidth to select

---

src/components/ListItemBase/ListItemBase.stories.tsx
src/components/ListItemBase/ListItemBase.tsx

Currently if the children of a list item base change (e.g one changes from button pill to button simple) then it is no longer navigable by keyboard. This change updates the navigable children when children changes.
I haven't added tests for this but I've added a storybook to demo the fix
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-471568

fix(list-item-base): update navigable children when children change

---

src/components/ListItemBase/ListItemBase.tsx

Simplify `ListItemBase` navigation in terms of getting the navigable children by finding them each key press. This removes the cache of them since the search is not expensive, and avoids issues with stale values in the cache.

fix: always get navigable children on pressing left or right

---

src/components/ListHeader/ListHeader.unit.test.tsx.snap
src/components/ListItemBase/ListItemBase.test.tsx
src/components/ListItemBase/ListItemBase.test.tsx.snap
src/components/ListItemBase/ListItemBase.tsx
src/components/ListItemBase/ListItemBase.utils.test.tsx
src/components/ListItemBase/ListItemBase.utils.tsx

Currently if a ListHeader is used outside of a ListNext context then it is included in the tab order of the page despite it not being interactive. This change makes it so that interactive=false implies tabIndex=-1 in ListItemBase
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-471953

fix(list-item-base): make non-interactive list items have tabIndex -1

---

src/components/NavigationTab/NavigationTab.style.scss

Fix(NavigationTab): Updated height and tab count positioning in expanded state

---

src/components/Card/Card.tsx
src/components/Card/Card.unit.test.tsx.snap

The scope of the changes in this pull request are focused on fixing the `static` value to not render a usable button, but instead, render the card as a `<div />`
* [SPARK-464621](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-464621)

fix(card): static as div

---

src/components/ThemeProvider/ThemeProvider.style.scss

The scope of the changes in this pull request are to fix Safari support for the provided Inter font. Without specifying the scope of a font-face, such as our `inter` font, safari only respects the default font size for a specific font (normal).
To reproduce this, open the *storybook* and browse to `text`. From `text`, add `font-weight` to the style of `750` while using the Safari browser.
* [Task](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-464615)

fix(fonts): safari support for inter

---

src/components/TextInput/TextInput.stories.tsx
src/components/TextInput/TextInput.tsx
src/components/TextInput/TextInput.types.ts
src/components/TextInput/TextInput.unit.test.tsx
src/components/TextInput/TextInput.unit.test.tsx.snap

To address, [SPARK-488197](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-488197), I added a inputMaxLen optional property to TextInput to allow consume to specify tha max amount of chars the UI should allow the user to input.

feat(text-input): add max len property

---

.vscode/settings.json
src/components/Reaction/Reaction.tsx
src/components/Reaction/Reaction.unit.test.tsx

fix(csp): use lottie-light to avoid eval()

---

src/components/NotificationSystem/NotificationSystem.unit.test.tsx.snap
src/components/ToastNotification/ToastNotification.constants.ts
src/components/ToastNotification/ToastNotification.stories.args.ts
src/components/ToastNotification/ToastNotification.tsx
src/components/ToastNotification/ToastNotification.types.ts
src/components/ToastNotification/ToastNotification.unit.test.tsx

Add new prop to ToastNotification to fix the missing accessible label on the close button
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-505339

fix: add close button accessible name props to ToastNotification

---

src/components/SearchInput/SearchInput.tsx
src/components/SearchInput/SearchInput.unit.test.tsx
src/components/SearchInput/SearchInput.unit.test.tsx.snap

This pull request addresses the bug where pressing the Tab key was not navigating to the "X" button on the Search textbox. Added the following props to `<ButtonSimple />` inside `<SearchInput />`
- Updated event listener to handle Tab key press by setting `useNativeKeyDown` to true
- Implemented logic to focus on the "X" button when Tab key is pressed by setting `excludeFromTabOrder` to false 
Press Tab to navigate to the “X” button on the Search textbox [SPARK-522081](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-522081)

Fix(SearchInput): Fix tab navigation to close button in SearchInput component

---

src/components/NotificationSystem/NotificationSystem.unit.test.tsx.snap
src/components/ToastNotification/ToastNotification.constants.ts
src/components/ToastNotification/ToastNotification.tsx
src/components/ToastNotification/ToastNotification.types.ts
src/components/ToastNotification/ToastNotification.unit.test.tsx
src/components/ToastNotification/ToastNotification.unit.test.tsx.snap

Removing a default label which I suggested in https://github.com/momentum-design/momentum-react-v2/pull/462/files as a string would not be translated in MRV2, so the default cannot exist on this repo.

feat(toast-notification): remove default label of close button

---

src/components/OverlayAlert/OverlayAlert.stories.args.ts
src/components/OverlayAlert/OverlayAlert.stories.docs.mdx
src/components/OverlayAlert/OverlayAlert.tsx
src/components/OverlayAlert/OverlayAlert.types.ts
src/components/OverlayAlert/OverlayAlert.unit.test.tsx
src/components/OverlayAlert/OverlayAlert.unit.test.tsx.snap

- Add ability to pass aria-label through to ModalContainer
- Add aria-labelledby to ModalContainer
- Apply this Id to title component
- Change header type to "title"
[SPARK-525340](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-525340)
[Tech Breakdown](https://confluence-eng-gpk2.cisco.com/conf/display/WTWC/Bucket+Breakdown+-+SPARK-522085+Overlays)

fix(overlay-alert): add ariaLabel prop, add aria-labelledby to ModalContainer and id to title text and change title from h3 to h2

---

src/legacy/Lightbox/index.js
src/legacy/Lightbox/tests/index.spec.js
src/legacy/Lightbox/tests/index.spec.js.snap

Making changes to a legacy component to fix accessibility.
Changed the title to be h2
Added id to title and aria-labelledby to modal
|Before|After|
|---|---|
|![Screenshot 2024-05-22 at 13 15 07](https://github.com/momentum-design/momentum-react-v2/assets/86778628/d3f98fe4-731b-469b-a161-e066a4022337)|![Screenshot 2024-05-22 at 13 15 05](https://github.com/momentum-design/momentum-react-v2/assets/86778628/fd7737ba-a1d1-4710-b0e3-03f7584ceefe)|
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526931
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-503204

fix(lightbox): change title to h2, add aria-labelledby and id for title

---

src/components/MenuTrigger/MenuTrigger.tsx
src/components/MenuTrigger/MenuTrigger.unit.test.tsx

- use aria-haspopup from triggerComponent props
- currently if you pass anything other than listbox or menu useMenuTrigger returns undefined, have added workaround for that so that id undefined is returned then we use triggerComponent prop
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-528433

fix(menutrigger): ariahaspopup can be passed from triggercomponent

---

src/components/List/List.stories.tsx
src/components/SearchInput/SearchInput.stories.args.ts
src/components/SearchInput/SearchInput.stories.tsx
src/components/SearchInput/SearchInput.types.ts
src/components/SearchInput/SearchInput.unit.test.tsx
src/components/SearchInput/SearchInput.unit.test.tsx.snap

BREAKING CHANGE: DO NOT MERGE IF YOU ARE NOT THE AUTHOR
On the SearchInput component, we need to require the consumer to pass a clearButtonAriaLabel property for when the user has added value to the input. This is an accessibilty requirement, as the clear button will always be a ButtonCircle with an X, so aria-label is needed to describe to the impaired user what would happen if he clicks on that X.
Cantina PR to handle breaking-changes:

do-no-merge feat(search-input): make clearButtonAriaLabel required

---

src/components/GlobalSearchInput/GlobalSearchInput.tsx
src/components/GlobalSearchInput/GlobalSearchInput.unit.test.tsx
src/components/GlobalSearchInput/GlobalSearchInput.unit.test.tsx.snap

We are using react-aria's useSearchField for the GlobalSearchInput component. However, this hook is returning a static true on the clear button excludeFromTabOrder, which makes this button not focusable and violating accessibilty rules.
I am overwriting this prop from react aria to false before passing it to the clear button. 
[*Links to relevent resources.*](https://github.com/adobe/react-spectrum/blob/02f242f41f0347b3f11e50b019c197127b7d0a08/packages/%40react-aria/searchfield/src/useSearchField.ts#L118)

feat(clear-button-index): overwrite react aria excludeFromTabOrder

---

src/components/AriaToolbar/AriaToolbar.stories.tsx
src/components/AriaToolbar/AriaToolbar.tsx
src/components/AriaToolbar/AriaToolbar.unit.test.tsx
src/components/AriaToolbar/AriaToolbar.unit.test.tsx.snap

- Fixed the aria toolbar, by allowing the keyDown event to propagate up (this is for fixing accessibility issues, when using a aria toolbar within a Popover)

fix: ariatoolbar propagate keydown

---

src/components/Icon/Icon.tsx
src/components/Icon/Icon.unit.test.tsx
src/components/Icon/Icon.unit.test.tsx.snap

I made a PR in order to pass ariaLabel correctly to an icon. I am also allowing the passing of aria-label to the icon, which should be treated the same way as aria-label. This is to not break the various places in Cantina where aria-label is already passed to an IconNext.

feat(icon-aria-label): allow aria-label to be used as accessible name

---

src/components/Select/Select.tsx
src/components/Select/Select.types.ts
src/components/Select/Select.unit.test.tsx
src/components/Select/Select.unit.test.tsx.snap

fix(selectNext): adding aria-label as prop

---

src/components/Coachmark/Coachmark.unit.test.tsx.snap
src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/components/ModalArrow/ModalArrow.tsx
src/components/ModalArrow/ModalArrow.unit.test.tsx
src/components/ModalArrow/ModalArrow.unit.test.tsx.snap
src/components/ModalContainer/ModalContainer.unit.test.tsx.snap
src/components/Popover/Popover.unit.test.tsx.snap

fix(images): add ariaHidden to ModalArrow to not be read by SR

---

src/components/Card/Card.stories.tsx
src/components/Card/Card.tsx
src/components/Card/Card.unit.test.tsx
src/components/Card/Card.unit.test.tsx.snap
src/components/MeetingContainer/MeetingContainer.unit.test.tsx.snap

The non-legacy Card component, which is currently not used in Cantina or in MRV2, renders an invisible cardStatus component even if there is no status to render. I am conditioning the render of this child component to only if colorStatus prop is passed to the parent.

feat(card): dont render status if not color status provided

---

src/components/TextInput/TextInput.tsx
src/components/TextInput/TextInput.unit.test.tsx
src/components/TextInput/TextInput.unit.test.tsx.snap

feat(textInput): Removed id from the whole wrapper of the component

---

src/components/Popover/Popover.tsx
src/components/Popover/Popover.unit.test.tsx
src/components/Popover/Popover.unit.test.tsx.snap
src/components/Tooltip/Tooltip.unit.test.tsx.snap
src/components/TooltipPopoverCombo/TooltipPopoverCombo.unit.test.tsx.snap

This is required when we have Popover as triggerComponent of a Popover. Fixes issues with aria-labelledby 
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-505193

fix(popover): fall back to parent id for noninteractive

---

src/components/Select/Select.tsx
src/components/Select/Select.unit.test.tsx
src/components/Select/Select.unit.test.tsx.snap

feat(SelectNext): aria-activedescendant added

---

src/components/RadioGroup/RadioGroup.tsx
src/components/RadioGroup/RadioGroup.unit.test.tsx
src/components/RadioGroup/RadioGroup.unit.test.tsx.snap
src/components/RadioSimpleGroup/RadioSimpleGroup.stories.tsx
src/components/RadioSimpleGroup/RadioSimpleGroup.tsx
src/components/RadioSimpleGroup/RadioSimpleGroup.unit.test.tsx
src/components/RadioSimpleGroup/RadioSimpleGroup.unit.test.tsx.snap

fix(RadioGroup): add aria-describedby

---

src/components/List/List.tsx
src/components/List/List.unit.test.tsx
src/components/Popover/Popover.stories.tsx
src/components/Popover/Popover.unit.test.tsx

Lists have keyboard event handling. This keyboard handling prevented the Escape keyboard event from reaching the window, where the popover closing plugin has the event handler.
This stopped Popovers closing when they were rendered inside of Lists

fix(list): fix escape event propagation for list

---

src/components/OverlayAlert/OverlayAlert.stories.tsx
src/components/OverlayAlert/OverlayAlert.tsx
src/components/OverlayAlert/OverlayAlert.unit.test.tsx
src/components/Popover/Popover.events.ts
src/components/Popover/tippy-plugins/hideOnEscPlugin.test.ts
src/components/Popover/tippy-plugins/hideOnEscPlugin.ts
src/hooks/useShouldCloseOnEsc.test.ts
src/hooks/useShouldCloseOnEsc.ts

This is to fix https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-503237
Issue: If there is a tooltip in an overlay alert then Esc will close the overlayalert first instead of the tooltip. To fix this the overlay alert has to be made aware of whether any popover instances are opened while it is rendered. We use events for this and we keep track of the number of instances open to know if onClose on the overlayalert should be fired or not.
This will also work for interactive popovers as long as hideonEsc is true.

fix(OverlayAlert): don't close overlay alert if popover is open inside

---

src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/components/Popover/LazyTippy.tsx
src/components/Popover/Popover.stories.tsx
src/components/Popover/Popover.tsx
src/components/Popover/Popover.types.ts
src/components/Popover/Popover.unit.test.tsx
src/components/Select/Select.unit.test.tsx.snap
src/components/TooltipPopoverCombo/TooltipPopoverCombo.unit.test.tsx.snap

Prior to this change, keyboard enter press popovers with nested triggers would open them both. We don't want this ordinarily. Added a new prop **continuePropagationOnTrigger** to re-enable this behavior if we decide we do have a case for it

fix(popover): disable propagation on trigger

---

src/components/TextInput/TextInput.tsx
src/components/TextInput/TextInput.unit.test.tsx
src/components/TextInput/TextInput.unit.test.tsx.snap

As part of [SPARK-367394](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-367394) (issue 2 of Other issues), they are asking us that:
Expected Result:
The Clear text button for each text field should have a unique label announced so the user understand to which input it refers to,
as Clear text <input label>
Actual result:
The Clear text button for each text field announces the same label and the user would not understand to which input it refers to,
as Clear text <input label>
For this, I have linked the X button with the input or its visible label using aria-labelledby
[SPARK-367394](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-367394)

feat(text-input): Link clear button with input

---

src/components/Tooltip/Tooltip.stories.args.ts
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/Tooltip.unit.test.tsx
src/components/Tooltip/Tooltip.unit.test.tsx.snap

Whe tooltip type was "description", we were relying on tippy's default logic to link trigger and tooltip with aria-describedby. But that was adding the id to the external tooltip layer and not to the modal itself. So SR was not reading the content when focus on the button.

feat(tooltip-description): tooltip type description

---

src/components/Popover/Popover.stories.args.ts
src/components/Popover/Popover.tsx
src/components/Popover/Popover.types.ts
src/components/Popover/Popover.unit.test.tsx
src/components/Popover/Popover.unit.test.tsx.snap
src/components/Toggletip/Toggletip.unit.test.tsx.snap
src/components/Tooltip/Tooltip.stories.args.ts
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/Tooltip.types.ts
src/components/Tooltip/Tooltip.unit.test.tsx
src/components/Tooltip/Tooltip.unit.test.tsx.snap
src/components/TooltipPopoverCombo/TooltipPopoverCombo.tsx
src/components/TooltipPopoverCombo/TooltipPopoverCombo.unit.test.tsx
src/components/TooltipPopoverCombo/TooltipPopoverCombo.unit.test.tsx.snap

This fixes the aria-labelledby chaining issue to provide the correct label for the popover in TooltipPopoverCombo, by allowing Popover to have aria-labelledby overridden and allowing Tooltip to have labelId overridden. This fix removes some duplicate and now-unnecessary ids.
This also removes the extra aria-haspopup which was incorrectly being added to the tooltip itself in TooltipPopoverCombo.
This also fixes Tooltip treating type none the same as type description.

fix(TooltipPopoverCombo): fix the aria-labelledby of the popover when the button has a tooltip

---

src/components/MenuTrigger/MenuTrigger.stories.args.ts
src/components/MenuTrigger/MenuTrigger.tsx
src/components/MenuTrigger/MenuTrigger.unit.test.tsx
src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/components/Popover/Popover.stories.args.ts
src/components/Popover/Popover.tsx
src/components/Popover/Popover.types.ts
src/components/Popover/Popover.unit.test.tsx
src/components/Popover/Popover.unit.test.tsx.snap

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-505185
https://sqbu-github.cisco.com/WebExSquared/webex-web-client/pull/5917
This is used for the positioning-only trigger for webex assistant. zIndex puts the assistant response popover slightly behind the webex assistant control popover. Added to MenuTrigger, just because other style-related props are. ariaLabel provides a label directly, as the positioning-only trigger cannot be used as aria-labelledby.

fix(PopoverNext): pass zIndex param to tippy, allow ariaLabel param to override default labelling

---

src/components/ButtonCircle/ButtonCircle.style.scss

Not sure when this broke, but sometime in the past 10 months. Icons on smaller ButtonCircles are not centred properly
|Before|After|
|---|---|
|![Screenshot 2024-07-01 at 11 44 49](https://github.com/momentum-design/momentum-react-v2/assets/86778628/7db53cfe-4282-47ad-bfd3-67c34c5bc5c5)|![Screenshot 2024-07-01 at 11 44 53](https://github.com/momentum-design/momentum-react-v2/assets/86778628/fbdb0995-5f97-4009-b8c1-93a8e3c1aeb3)|
This will fix the following issues
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-538760
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-538761
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-538762
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-538764
and possible others I've missed in the app

fix(button-circle): justify content in center

---

src/components/OverlayAlert/OverlayAlert.unit.test.tsx
src/components/Popover/tippy-plugins/hideOnEscPlugin.ts
src/hooks/useShouldCloseOnEsc.ts

There was a race condition where
1. TooltipPopoverCombo opened
2. Item in Popover opened an OverlyAlert
3. Popover closed
4. OverlayAlert opened and started tracking popover instances
5. Tooltip of TooltipPopoverCombo opened
6. OverlayAlert couldn't close because the tooltip was supposedly open (although not visible...)
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-538778

fix(overlay-alert): fix for OverlayAlert closing if triggerElement is TooltipPopoverCombo

---

src/components/MenuTrigger/MenuTrigger.tsx
src/components/MenuTrigger/MenuTrigger.unit.test.tsx
src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap

Exposes triggerComponentRef which references the button element, this is required by Cantina when the trigger button opens a modal and that modal opens another modal - on closing 2nd modal we should have reference to this trigger button to focus back

feat(menutrigger): expose triggerComponentRef which ref to button

---

src/components/Text/Text.stories.tsx
src/components/Text/Text.tsx
src/components/Text/Text.types.ts
src/components/Text/Text.unit.test.tsx
src/components/Text/Text.unit.test.tsx.snap

Add the prop tagName to allow the overriding of the tag used for the text component. The tagName prop is optional and if not supplied, the default tagName for each type will be used.

feat(text): tagName prop to override to tag

---

src/components/Toast/Toast.constants.ts
src/components/Toast/Toast.stories.args.ts
src/components/Toast/Toast.stories.tsx
src/components/Toast/Toast.style.scss
src/components/Toast/Toast.tsx
src/components/Toast/Toast.types.ts
src/components/Toast/Toast.unit.test.tsx
src/components/Toast/Toast.unit.test.tsx.snap

fix(toast): use text to have proper tag

---

src/components/CodeInput/CodeInput.tsx
src/components/CodeInput/CodeInput.types.ts
src/components/CodeInput/CodeInput.unit.test.tsx
src/components/CodeInput/CodeInput.unit.test.tsx.snap

fix(): adding aria-label and aria-describedby to input props

---

src/components/AriaToolbar/AriaToolbar.constants.ts
src/components/AriaToolbar/AriaToolbar.stories.args.ts
src/components/AriaToolbar/AriaToolbar.stories.tsx
src/components/AriaToolbar/AriaToolbar.tsx
src/components/AriaToolbar/AriaToolbar.types.ts
src/components/AriaToolbar/AriaToolbar.unit.test.tsx
src/components/AriaToolbar/AriaToolbar.unit.test.tsx.snap
src/components/AriaToolbar/AriaToolbar.utils.ts
src/components/AriaToolbarItem/AriaToolbarItem.tsx
src/components/AriaToolbarItem/AriaToolbarItem.types.ts
src/components/AriaToolbarItem/AriaToolbarItem.unit.test.tsx
src/components/AriaToolbarItem/AriaToolbarItem.unit.test.tsx.snap
src/components/AriaToolbarItem/index.ts
src/components/Avatar/Avatar.unit.test.tsx
src/components/Avatar/Avatar.unit.test.tsx.snap
src/components/OverlayAlert/OverlayAlert.stories.tsx
src/components/Popover/Popover.stories.tsx
src/components/ReactionButton/ReactionButton.style.scss
src/components/ReactionButton/ReactionButton.tsx
src/components/ReactionButton/ReactionButton.unit.test.tsx.snap
src/components/ReactionPicker/ReactionPicker.stories.tsx
src/components/ReactionPicker/ReactionPicker.style.scss
src/components/ReactionPicker/ReactionPicker.tsx
src/components/ReactionPicker/ReactionPicker.types.ts
src/components/ReactionPicker/ReactionPicker.unit.test.tsx
src/components/ReactionPicker/ReactionPicker.unit.test.tsx.snap
src/components/index.ts
src/index.js
src/utils/useProvidedRef.test.ts
src/utils/useProvidedRef.ts

> [!CAUTION]
> This PR is introducing **Breaking Changes**
PR With Cantina migration will be raised soon. (to accompany the release of this new changes).
- refactor AriaToolbar
- introduce new AriaToolbarItem to be able to explicitly describe which elements are the toolbar items (this is useful in situations where we might have Popovers, or Tooltips as immediate children to the AriaToolbar component. Previously it assumes that the immediate children is the actual button, but that's not the case all the time.
- add direct support for automatic wrap aria toolbar in button group, to facilitate easier styling (out of the box)
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-505327

feat(reaction-aria-toolbar): changes

---

src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/Checkbox.types.ts
src/components/Checkbox/Checkbox.unit.test.tsx

fix(Checkbox): aria-label null if there's no label

---

src/legacy/AlertContainer/index.js
src/legacy/AlertContainer/tests/index.spec.js
src/legacy/AlertContainer/tests/index.spec.js.snap

Fix the alertcontainer by converting it to a section and apply a aria-label to it, which makes it a role=region.
This fix had to be made to the legacy component, since its still in use.

fix(a11y): alertcontainer-region

---

src/components/NotificationSystem/NotificationSystem.unit.test.tsx.snap
src/components/ToastNotification/ToastNotification.tsx
src/components/ToastNotification/ToastNotification.unit.test.tsx.snap

Due to the change in the Modalcontainer the ToastNotification component also has now a role="dialog" set (since ModalContainer is used for it). This is not correct, since the toast is not supposed to be role="dialog", but role="alert" (which gets inferred by Tippy). In this case i have overridden the role with "generic" and set ariaModal to false to remove all the overrides (i couldn't find a better way without changing too much implementation)

fix(a11y): toastnotification role override

---

src/components/AriaToolbarItem/AriaToolbarItem.tsx
src/components/AriaToolbarItem/AriaToolbarItem.unit.test.tsx

props specified on the children should take precedent over what's passed into the toolbar item

fix(aria-toolbar-item): extra props should be passed to children but not override children props

---

src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/Checkbox.unit.test.tsx.snap

- According to a11y duplicate id's should be avoided. At the moment the id is passed to the label and input. This fix will make sure to pass through the id only to the label, not the input itself to avoid duplication. This is also tested by the a11y tests in Storybook (not failing anymore with this fix).

fix(a11y): checkbox id duplicate

---

src/components/ButtonCircleToggle/ButtonCircleToggle.constants.ts
src/components/ButtonCircleToggle/ButtonCircleToggle.tsx
src/components/ButtonCircleToggle/ButtonCircleToggle.types.ts
src/components/ButtonCircleToggle/ButtonCircleToggle.unit.test.tsx
src/components/ButtonCircleToggle/ButtonCircleToggle.unit.test.tsx.snap
src/components/ButtonPillToggle/ButtonPillToggle.constants.ts
src/components/ButtonPillToggle/ButtonPillToggle.tsx
src/components/ButtonPillToggle/ButtonPillToggle.types.ts
src/components/ButtonPillToggle/ButtonPillToggle.unit.test.tsx
src/components/ButtonPillToggle/ButtonPillToggle.unit.test.tsx.snap
src/storybook/helper.stories.argtypes.ts

In ButtonCircleToggle and ButtonPillToggle, add ariaStateKey prop to determine whether aria-pressed or aria-expanded is used for selected state
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-505240 (see comment)

fix(toggle buttons): add ariaStateKey prop to determine whether aria-pressed or aria-expanded is used for selected state

---

src/components/Link/Link.stories.args.ts
src/components/Link/Link.tsx
src/components/Link/Link.types.ts
src/components/Link/Link.unit.test.tsx

When a consumer uses a Link without an href attribute, only using onPress to open a new tab, the user cannot focus on the Link.So, add tabIndex for Link component.

feat: add tabIndex for Link component

---

src/legacy/Lightbox/index.js
src/legacy/Lightbox/tests/index.spec.js.snap

- Remove the unnecessary click on Lightbox which lets the lightbox close (it is not accessible)
- This will fix existing a11y issues
- Updating snapshot

fix(a11y): lightbox remove unnecessary click

---

src/components/Popover/Popover.constants.ts
src/components/Popover/Popover.tsx
src/components/Popover/Popover.types.ts
src/components/Popover/Popover.unit.test.tsx

- add prop to disable react-aria focus scoping inside the popover. We need this because at the moment it doesn't have support for shadow-dom, and some of our 3rd party components are built using web-components.
- this will allow us to add our custom focus lock for web-components without interfering with react-aria's focus scope implementation.
Issue on react-aria: https://github.com/adobe/react-spectrum/issues/1472
PR with potential future solution: https://github.com/adobe/react-spectrum/pull/6046 (it's recent but not sure how long it will take until this gets released).

feat(popover): add disable focus lock

---

src/components/SearchInput/SearchInput.constants.ts
src/components/SearchInput/SearchInput.tsx
src/components/SearchInput/SearchInput.types.ts
src/components/SearchInput/SearchInput.unit.test.tsx
src/components/SearchInput/SearchInput.unit.test.tsx.snap

- adds aria-controls, aria-expanded (isExpanded), isCombobox, and 'combobox' role to SearchInput
- three warnings for usage of isCombobox, controls, and isExpanded
- types and unit testing
- updated snapshots accordingly

fix(a11y): aria changes in searchinput

---

src/components/ButtonControl/ButtonControl.tsx
src/components/OverlayAlert/OverlayAlert.style.scss

- add ref forwarding to button control
- also fixing a minor visual bug where the hover bg color of the last button control in an overlay alert exceeds the overlay boundaries
before:
after:

feat(button-control): add ref forwarding

---

src/components/Select/Select.tsx
src/components/Select/Select.types.ts
src/components/Select/Select.unit.test.tsx

fix(select): optionally overwrite ariaLabelledBy

---

src/components/OverlayAlert/OverlayAlert.style.scss

noticed when doing https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-555472

fix(overlay-alert): missing gap in the header when there are no controls

---

src/components/SearchInput/SearchInput.tsx
src/components/SearchInput/SearchInput.unit.test.tsx

fix(SearchInput): propagate enter key: 

---

src/components/Avatar/Avatar.stories.args.tsx
src/components/Avatar/Avatar.tsx
src/components/Avatar/Avatar.types.ts
src/components/Avatar/Avatar.unit.test.tsx
src/components/Avatar/Avatar.unit.test.tsx.snap

- Allow passing in a buttonClassName to override the classname of the button of the avatar
- This is required to fix a a11y issue.

fix(avatar): avatar add buttonclassname prop

---

src/components/SearchInput/SearchInput.tsx
src/components/SearchInput/SearchInput.unit.test.tsx
src/components/SearchInput/SearchInput.unit.test.tsx.snap

fix(searchInput): id should be unique: SPARK-551735

---

package.json
yarn.lock

fix(deps): upgrade react-focus-lock

---

src/components/Popover/tippy-plugins/hideOnBlurPlugin.test.ts
src/components/Popover/tippy-plugins/hideOnBlurPlugin.ts

* the focusOut event listener should be removed when the tippy instance is destroyed, not hidden. if done onHidden, blur handling only works once since the event listener gets removed onHidden.
* https://atomiks.github.io/tippyjs/v6/all-props/#ondestroy

fix(popover): remove event listener onDestroy, not onHidden

---

src/components/SearchInput/SearchInput.tsx
src/components/SearchInput/SearchInput.types.ts
src/components/SearchInput/SearchInput.unit.test.tsx

* allow SearchInput to accept an onKeyDown prop. the parent component may want the ability to act on keydown, for example, when pressing "down" from input may need to switch focus to a result

feat(searchinput): allow searchinput to accept an onkeydown prop

---

src/components/Menu/Menu.stories.tsx
src/components/Menu/Menu.tsx
src/components/Menu/Menu.unit.test.tsx
src/components/Menu/Menu.unit.test.tsx.snap
src/components/MenuItem/MenuItem.tsx
src/components/MenuItem/MenuItem.types.ts
src/components/MenuSection/MenuSection.tsx
src/components/MenuSection/MenuSection.types.ts
src/components/MenuSection/MenuSection.unit.test.tsx.snap
src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/hooks/useOrientationBasedKeyboardNavigation.ts

1. Removing Multimenu story as we are no longer going to follow the approach of having more than 1 menu on a single popover.
2. For the previous reason, we are no longer needing the isGroupRole prop on Menu.
3. Google Chrome Settings Menu has horizontally displayed items that are navigated using up and down arrow key. For that reason, we are removing the orientation prop from Menu as we no longer need to enforce the kb navigation to left-right if the items are horizontally displayed.
4. We are removing any List/ul traces from Menu. We realized menus with sections had 3 layers of ul's without any purpose. 
5. We are letting menu navigation be dictated by react-aria useMenu hook, and not by list navigation hooks. For that reason, we are also removing itemIndex prop from MenuSection and …

fix(Menu): Keyboard navigation fix for menus with multiple sections

---

src/components/Menu/Menu.tsx
src/components/Menu/Menu.types.ts
src/components/Menu/Menu.unit.test.tsx

As part of https://github.com/momentum-design/momentum-react-v2/pull/624 , we are removing the types from Menu component to rely fully on useMenu keyboard behaviour and role assignment.

feat(menu): remove tabIndex, orientation and isGroupRole from types

---

src/components/SearchInput/SearchInput.tsx
src/components/SearchInput/SearchInput.types.ts
src/components/SearchInput/SearchInput.unit.test.tsx

accept and pass additional props into the search icon
will be used in cantina to specify the aria label of the search icon
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-505795

feat(search-input): accept additional search icon props

---

scss/tools/mixins/focus.scss
src/components/Checkbox/Checkbox.style.scss
src/components/FocusRing/FocusRing.style.scss
src/components/NavigationTab/NavigationTab.style.scss
src/components/Tab/Tab.style.scss
src/components/ThemeProvider/ThemeProvider.style.scss

When Windows High Contrast mode is enabled, certain CSS properties are forced to have certain values. One of these is `box-shadow` which is forced to `none`.
`box-shadow` is used to display the focused element therefore we need a alternative. Since `outline` is already forced to none when using the `focus-styles` mixin, we can use it to display a focus ring.
Unfocused:
Focused:
---
Unfocused:
Focused:
---
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors
Should fix a couple of issues raised here:
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-506028

style(high-contrast): add focus outline, checkbox styles and tab active styles in high contrast mode

---

src/components/SpaceTreeNode/SpaceTreeNode.unit.test.tsx.snap
src/components/Tree/Tree.test.tsx
src/components/Tree/Tree.test.tsx.snap
src/components/Tree/Tree.tsx
src/components/Tree/Tree.types.ts
src/components/Tree/Tree.utils.test.tsx
src/components/Tree/Tree.utils.ts
src/components/TreeNodeBase/TreeNodeBase.test.tsx.snap
src/components/TreeNodeBase/TreeNodeBase.tsx

When the tree structure updated Tree will migrate the state of the nodes which are remain in the new structure.
It fixes the use case, when a node moves from an open node under a closed one.

fix: tree component migrate open/close state

---

src/components/OverlayAlert/OverlayAlert.stories.args.ts
src/components/OverlayAlert/OverlayAlert.tsx
src/components/OverlayAlert/OverlayAlert.types.ts
src/components/OverlayAlert/OverlayAlert.unit.test.tsx
src/components/OverlayAlert/OverlayAlert.unit.test.tsx.snap

Added ariaLabelledby and ariaDescribedby props to OverlayAlert to allow the default behavior to be overwritten as needed.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-563063

feat(overlay-alert): add aria props

---

src/components/MeetingListItem/MeetingListItem.constants.ts
src/components/MeetingListItem/MeetingListItem.style.scss
src/components/MeetingListItem/MeetingListItem.tsx
src/components/MeetingListItem/MeetingListItem.unit.test.tsx.snap
src/components/MeetingRowContent/MeetingRowContent.constants.ts
src/components/MeetingRowContent/MeetingRowContent.stories.args.ts
src/components/MeetingRowContent/MeetingRowContent.stories.docs.mdx
src/components/MeetingRowContent/MeetingRowContent.stories.tsx
src/components/MeetingRowContent/MeetingRowContent.style.scss
src/components/MeetingRowContent/MeetingRowContent.tsx
src/components/MeetingRowContent/MeetingRowContent.types.ts
src/components/MeetingRowContent/MeetingRowContent.unit.test.tsx
src/components/MeetingRowContent/MeetingRowContent.unit.test.tsx.snap
src/components/MeetingRowContent/index.ts
src/components/index.ts
src/index.js
src/storybook/helper.stories.templates.tsx

This is to fix a bug in ActivityList refactor where the MeetingListItem is causing issues as it's not immediately wrapped in a ListNext component. To solve this we will just use MeetingRowContent in Cantina inside ActivityList and style it as if it were a MeetingListItem.

feat(meeting-row-content): add MeetingRowContent component and consume in MeetingListItem

---

src/components/SpaceTreeNode/SpaceTreeNode.unit.test.tsx.snap
src/components/Tree/Tree.stories.docs.mdx
src/components/Tree/Tree.stories.tsx
src/components/Tree/Tree.test.tsx
src/components/Tree/Tree.test.tsx.snap
src/components/Tree/Tree.tsx
src/components/Tree/Tree.types.ts
src/components/Tree/Tree.utils.test.tsx
src/components/Tree/Tree.utils.ts
src/components/TreeNodeBase/TreeNodeBase.stories.docs.mdx
src/components/TreeNodeBase/TreeNodeBase.test.tsx
src/components/TreeNodeBase/TreeNodeBase.test.tsx.snap
src/components/TreeNodeBase/TreeNodeBase.tsx
src/hooks/useItemSelected.ts
src/index.js
src/utils/navigation.test.ts
src/utils/navigation.ts

TreeNodeBase change tabindex of all interactable elements, but this can change elements which are under focus management,
eg. Menu, nested lists, etc.

fix: preserve tabindex for specified elements

---

config/typescript/tsconfig.base.json
package.json
src/components/Avatar/Avatar.types.ts
src/components/Avatar/Avatar.unit.test.tsx
src/components/Avatar/Presence.tsx
src/components/Avatar/Presence.utils.ts
src/components/AvatarMeetingsListItem/AvatarMeetingsListItem.tsx
src/components/AvatarMeetingsListItem/AvatarMeetingsListItem.unit.test.tsx
src/components/AvatarMeetingsListItem/AvatarMeetingsListItem.unit.test.tsx.snap
src/components/ButtonControl/ButtonControl.tsx
src/components/Coachmark/Coachmark.types.ts
src/components/Icon/Icon.constants.ts
src/components/Icon/Icon.tsx
src/components/Icon/Icon.types.ts
src/components/Icon/Icon.unit.test.tsx
src/components/Icon/Icon.unit.test.tsx.snap
src/components/Icon/Icon.utils.test.ts
src/components/Icon/Icon.utils.ts
src/components/LoadingSpinner/LoadingSpinner.tsx
src/components/LoadingSpinner/LoadingSpinner.unit.test.tsx.snap
src/components/NavigationTab/NavigationTab.types.ts
src/components/Reaction/Reaction.unit.test.tsx.snap
src/components/SearchInput/SearchInput.unit.test.tsx.snap
src/components/TextToast/TextToast.unit.test.tsx
yarn.lock

feat(icon): use icon type names

---

src/components/Tree/Tree.test.tsx
src/components/Tree/Tree.tsx
src/components/Tree/Tree.utils.test.tsx
src/components/Tree/Tree.utils.ts
src/components/TreeNodeBase/TreeNodeBase.test.tsx
src/components/TreeNodeBase/TreeNodeBase.test.tsx.snap
src/components/TreeNodeBase/TreeNodeBase.tsx

- add aria-labelledby to each group nodes
- removed error throwing when TreeNodeBase is not wrapped with TreeContext
[*Links to relevent resources.*](issue: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-506156)

fix: missing group aria label

---

scss/components/list-item/mixins.scss

Add font-weight: 700 when a menu item is active as per Figma. This also addresses an a11y color contrast issue.
Before | After
--- | ---
Jira Ticket: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-367582
- Issues 6 & 7
Figma: https://www.figma.com/design/FmXv8xvun1xAZiOMfztwqg/%F0%9F%A7%A9-Webex-App---Web?m=auto&node-id=5431-1707&t=QziLFquo50T9wcRC-1

fix(legacy/ListItem): add font-weight when menu item is active for a11y

---

src/components/SpaceTreeNode/SpaceTreeNode.unit.test.tsx.snap
src/components/Tree/Tree.constants.ts
src/components/Tree/Tree.hooks.tsx
src/components/Tree/Tree.test.tsx
src/components/Tree/Tree.tsx
src/components/Tree/Tree.types.ts
src/components/Tree/Tree.utils.test.tsx
src/components/TreeNodeBase/TreeNodeBase.constants.ts
src/components/TreeNodeBase/TreeNodeBase.style.scss
src/components/TreeNodeBase/TreeNodeBase.test.tsx
src/components/TreeNodeBase/TreeNodeBase.test.tsx.snap
src/components/TreeNodeBase/TreeNodeBase.tsx

In some case, for example on high CPU load the scroll to active node can not keep up with the user input and the active element removed because it is not in the view.
- check and scroll to active element when it is not in the DOM after each arrow key event.
- optimize MutationObserver creation

fix: tree component focus loss issue

---

src/components/Tree/Tree.test.tsx
src/components/Tree/Tree.tsx
src/components/Tree/Tree.utils.test.tsx
src/components/Tree/Tree.utils.ts

if selection mode is single, and 1 item is selected, and that item exists in the tree, then the initial focus should land on that item instead of the first item in the tree
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-503141

feat(tree): initial focus on selected item

---

src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/components/ModalContainer/ModalContainer.tsx
src/components/ModalContainer/ModalContainer.types.ts
src/components/ModalContainer/ModalContainer.unit.test.tsx.snap
src/components/NotificationSystem/NotificationSystem.unit.test.tsx.snap
src/components/Popover/Popover.tsx
src/components/Popover/Popover.types.ts
src/components/Select/Select.unit.test.tsx.snap
src/components/ToastNotification/ToastNotification.unit.test.tsx.snap
src/components/Tooltip/Tooltip.unit.test.tsx.snap

This PR does the following:
- Removes the aria-modal property from ModalContainer if the role is not a `dialog` or `alertdialog`.
- Removes aria-label and aria-labelledby properties from Popover if the role is `generic`, `presentation`, `none`. By specification, these roles cannot have any accessible name.
- Updates the type definition of ModalContainer and Popover to use AriaRole as the type for role
Jira Ticket (comment to address): https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-505153?focusedId=6541811&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-6541811
`aria-label` / `aria-labelledby` shouldn't be on:
`generic` - https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/generic_role#sect2
`presentation/none` - …

fix(Popover): remove aria-modal from non-dialogs and don't output aria-label on presentational elements

---

package.json
src/components/GlobalSearchInput/GlobalSearchInput.style.scss
src/components/SearchInput/SearchInput.style.scss
src/components/TextInput/TextInput.style.scss
yarn.lock

This PR updates the `::selection` styles for GlobalSearchInput, SearchInput and TextInput. This requires upgrading `@momentum-design/tokens` to the latest version since the `--mds-color-theme-background-accent-active` token doesn't exist in 0.0.77.
Jira Ticket: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-367516 (Issue 1)
Figma Design: https://www.figma.com/design/FmXv8xvun1xAZiOMfztwqg/%F0%9F%A7%A9-Webex-App---Web?m=auto&node-id=68975-21109&t=sK40uXTpBDHnoLie-1

fix(input-selection): add text selection styles for inputs

---

src/components/AlertBanner/AlertBanner.stories.docs.mdx
src/components/AlertBanner/AlertBanner.tsx
src/components/AlertBanner/AlertBanner.types.ts
src/components/AlertBanner/AlertBanner.unit.test.tsx
src/components/AlertBanner/AlertBanner.unit.test.tsx.snap

fix(alertbanner): change children type to ReactNnode

---

src/components/AriaToolbar/AriaToolbar.constants.ts
src/components/AriaToolbar/AriaToolbar.tsx
src/components/AriaToolbar/AriaToolbar.unit.test.tsx
src/components/AriaToolbar/AriaToolbar.unit.test.tsx.snap
src/components/ReactionPicker/ReactionPicker.unit.test.tsx.snap

it was once missing, now it's not
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-569589

fix(toolbar): missing aria orientation attribute

---

src/components/TextInput/TextInput.tsx
src/components/TextInput/TextInput.unit.test.tsx
src/components/TextInput/TextInput.unit.test.tsx.snap

Remove the clear input button when TextInput is disabled. This is based on the Figma not having the clear input button when the input is set as readonly.
Jira Ticket: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-389115
Figma: https://www.figma.com/design/FmXv8xvun1xAZiOMfztwqg/%F0%9F%A7%A9-Webex-App---Web?m=auto&node-id=66338-9556&t=N8ZWieRTPqVwXH0k-1

fix(TextInput): remove clear input button if TextInput is disabled

---

src/components/ButtonGroup/ButtonGroup.types.ts
src/components/ButtonSimple/ButtonSimple.types.ts
src/components/List/List.types.ts
src/components/ListItemBase/ListItemBase.types.ts

A small PR to update the types of components to use AriaRole instead of string for the role property.

fix(types): use AriaRole instead of string for role prop

---

src/components/SpaceRowContent/SpaceRowContent.style.scss

an earlier change updated the element types of the text, leading to unwanted styles applied on the wrong elements
before:
after:
I've also verified that it's working for compact / non-compact mode, as well as on narrow / wide displays:
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-573770

fix(space-list-content): compact mode text layout issue

---

src/components/Tree/Tree.test.tsx
src/components/Tree/Tree.tsx

bug: (virtualized tree) after clicking on a node, then scrolling away to click on another node, the tree attempts to scroll back to the last selected node
cause: for keyboard users, it's important that the node is rendered in the virtualized tree, thus there's some code that makes the virtualized tree scroll to the active node if focus comes within the tree. however, this caused the bug above
fix: we don't do the scrolling thing IF the focus is on / within another tree node
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-573336

fix(tree): stop scrolling away when selecting a new node in virtualized tree

---

src/components/Avatar/Avatar.style.scss
src/components/Badge/Badge.style.scss
src/components/ButtonCircleToggle/ButtonCircleToggle.style.scss
src/components/ButtonPillToggle/ButtonPillToggle.style.scss
src/components/FocusRing/FocusRing.style.scss
src/components/Icon/Icon.style.scss
src/components/ListItemBase/ListItemBase.style.scss
src/components/NavigationTab/NavigationTab.style.scss
src/components/RadioSimple/RadioSimple.style.scss
src/components/Tab/Tab.style.scss
src/components/ThemeProvider/ThemeProvider.style.scss
src/components/TreeNodeBase/TreeNodeBase.style.scss

This PR introduces the following changes, only for Windows High Contrast:
- Added SelectedItem system colors to active state of RadioSimple
- Added SelectedItem system colors to active state of ListItemBase
- Added SelectedItem system colors to selected state of TreeNodeBase
- Added AccentColor system colors to Badge
- Added SelectedItem system colors to active state of ButtonCircleToggle
- Added SelectedItem system colors to active state of ButtonPillToggle
- Tell the browser not to override the avatar background colors
Jira Ticket: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-506028
Confluence: https://confluence-eng-gpk2.cisco.com/conf/pages/viewpage.action?pageId=546082395
System Color Definition: https://drafts.csswg.org/css-color/#css-system-colors

fix: add high contrast colors, mainly around active/selected states

---

src/components/SpaceTreeNode/SpaceTreeNode.style.scss

fix(space-tree-node): read vs unread text should have different colors

---

src/legacy/Lightbox/index.js
src/legacy/Lightbox/tests/index.spec.js.snap

fix(SPARK-573927): add text color judgment in light theme

---

src/legacy/Lightbox/tests/index.spec.js.snap

Fix broken snapshot for legacy lightbox component. This was due to the jest downgrade, the up to date version (29.7.0) uses `{}` to represent objects whereas the version mrv2 uses now (26.6.3) uses `Object {}`

test(Lightbox): fix broken tests due to jest downgrade

---

scss/components/list-separator/list-separator.scss
src/legacy/ListSeparator/index.js
src/legacy/ListSeparator/tests/index.spec.js

Remove `font-weight: 250` from legacy list separator component.
Before:
After:
Jira Ticket: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-579344
Figma Design: https://www.figma.com/design/FmXv8xvun1xAZiOMfztwqg/%F0%9F%A7%A9-Webex-App---Web?m=auto&node-id=5585-13072&t=oauxKqnz3RqbQApS-1

fix(legacy/list-separator): remove low font-weight

---

src/components/AlertBanner/AlertBanner.tsx
src/components/AlertBanner/AlertBanner.unit.test.tsx

fix(alertbanner): add other props for alert banner

---

src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.stories.args.ts
src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.stories.tsx

This PR fixes the Screen Reader Announcer docs page. Currently it crashes when trying to load due to duplicate screen reader identities. This PR makes the doc use iframes instead of inline loading the components.

fix(ScreenReaderAnnouncer): fix storybook docs page

---

src/components/FocusRing/FocusRing.stories.args.ts
src/components/ListItemBase/ListItemBase.tsx
src/components/Menu/Menu.stories.args.ts
src/components/Menu/Menu.tsx
src/components/Menu/Menu.types.ts
src/components/Menu/Menu.unit.test.tsx
src/components/Menu/Menu.unit.test.tsx.snap

feat(menu): add prop for inset focus ring

---

src/components/TooltipPopoverCombo/TooltipPopoverCombo.stories.tsx
src/components/TooltipPopoverCombo/TooltipPopoverCombo.tsx
src/components/TooltipPopoverCombo/TooltipPopoverCombo.types.ts
src/components/TooltipPopoverCombo/TooltipPopoverCombo.unit.test.tsx
src/components/TooltipPopoverCombo/TooltipPopoverCombo.unit.test.tsx.snap

Add `type` prop back to otherTooltipProps.
If the type is set to "description", use the button as the label for the Popover instead of the Tooltip.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-584297

fix(TooltipPopoverCombo): allow type prop in otherTooltipProps

---

src/components/ComboBox/ComboBox.unit.test.tsx
src/components/ComboBox/ComboBox.unit.test.tsx.snap
src/components/InputMessage/InputMessage.tsx
src/components/InputMessage/InputMessage.unit.test.tsx.snap
src/components/SearchInput/SearchInput.unit.test.tsx.snap
src/components/TextInput/TextInput.tsx
src/components/TextInput/TextInput.unit.test.tsx
src/components/TextInput/TextInput.unit.test.tsx.snap

As we can see in the a11y audit reports, if an error gets displayed related to an input, this should be announced automatically by SR. 
[*Links to relevent resources.*](https://confluence-eng-gpk2.cisco.com/conf/display/WTWC/2.+INPUTS#:~:text=%E2%9A%AA%20ALLOW%20SR%20TO%20ANNOUNCE%20IF%20A%20TEXT%20INPUT%20HAS%20AN%20ERROR)

feat(text-input): add sr automatic announcement on error message

---

src/components/ListBoxBase/ListBoxBase.tsx
src/components/ListBoxItem/ListBoxItem.tsx

Set the `shouldSelectOnPressUp` option for `useSelect` hook to false to stop select options to be chosen on the pressUp event.
Fixes automatically selecting an option when the viewport is small enough for the options to render above the dropdown.
Also moves the option out of ListBoxItem and into ListBoxBase since it is deprecated in the `useOption` hook
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-577692

fix(ListBoxBase): set shouldSelectOnPressUp to false

---

src/components/Popover/Popover.stories.tsx
src/components/Popover/Popover.tsx
src/components/Popover/Popover.types.ts
src/components/Popover/Popover.unit.test.tsx
src/components/Popover/Popover.utils.test.ts
src/components/Popover/Popover.utils.ts
src/components/Popover/tippy-plugins/singleOpenPlugin.test.ts
src/components/Popover/tippy-plugins/singleOpenPlugin.ts
src/components/Select/Select.tsx
src/components/Select/Select.types.ts
src/components/Select/Select.unit.test.tsx

fix(select): fix multi select popovers within parent popover

---

src/components/TextInput/TextInput.tsx

Many times I have seen devs falling into adding the same string to the label and to the aria-label with the aim of ensuring a11y. That would, however, open an a11y bug as SR would read the same string twice when focusing on the input. 
To avoid that, we have added a console warn.
SPARK-582966

feat(TextInput): add warning if aria label and label are same

---

src/components/Coachmark/Coachmark.types.ts
src/components/Popover/Popover.types.ts
src/components/Popover/Popover.typetest.ts
src/components/Popover/Popover.unit.test.tsx
src/components/Popover/Popover.unit.test.tsx.snap
src/components/Popover/tippy-plugins/hideOnBlurPlugin.ts
src/components/TooltipPopoverCombo/TooltipPopoverCombo.types.ts

Use types to make aria-label mandatory for popover close button when present, and modify types which derive from Popover.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-582991

feat(a11y): make aria-label mandatory for popover close button when present

---

src/components/Avatar/Avatar.types.ts

size prop comment had default as 32, the actual default is 24.

fix(Avatar): update default size in comment

---

src/components/NotificationSystem/NotificationSystem.stories.tsx
src/components/NotificationSystem/NotificationSystem.tsx
src/components/NotificationSystem/NotificationSystem.types.ts
src/components/NotificationSystem/NotificationSystem.unit.test.tsx
src/components/NotificationSystem/NotificationSystem.unit.test.tsx.snap
src/components/NotificationSystem/NotificationSystem.utils.test.tsx
src/components/NotificationSystem/NotificationSystem.utils.ts

feat(notification-system): add screen reader announcer

---

src/components/SpaceTreeNode/SpaceTreeNode.stories.tsx
src/components/SpaceTreeNode/SpaceTreeNode.unit.test.tsx
src/components/SpaceTreeNode/SpaceTreeNode.unit.test.tsx.snap
src/components/Tree/Tree.stories.tsx
src/components/Tree/Tree.test.tsx
src/components/Tree/Tree.test.tsx.snap
src/components/Tree/Tree.tsx
src/components/Tree/Tree.types.ts
src/components/Tree/Tree.typetest.ts
src/components/TreeNodeBase/TreeNodeBase.stories.tsx
src/components/TreeNodeBase/TreeNodeBase.test.tsx
src/components/TreeNodeBase/TreeNodeBase.test.tsx.snap

Require aria-label or aria-labelledby in Tree Props type. Unfortunately this union type doesn't survive going through forwardRef, so I also added a console warning.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-582999

feat(a11y): require Tree aria-label or aria-labelledby

---

src/components/MeetingListItem/MeetingListItem.stories.tsx
src/components/MeetingRowContent/MeetingRowContent.style.scss

when the text in calendar list is too long, it will overlap.
add grid layout to meeting-list-item to adapt different length
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-600759

fix(MeetingRowContent): use grid layout to adapt different length

---

src/components/List/List.constants.ts
src/components/List/List.stories.tsx
src/components/List/List.tsx
src/components/List/List.types.ts
src/components/List/List.unit.test.tsx
src/components/List/List.utils.tsx
src/components/ListItemBase/ListItemBase.test.tsx
src/components/ListItemBase/ListItemBase.tsx
src/components/ListItemBase/ListItemBase.types.ts
src/hooks/useOrientationBasedKeyboardNavigation.test.ts
src/hooks/useOrientationBasedKeyboardNavigation.ts

Allow non-numeric item indexes in the list. This is helpful for rendering parts of a list where each item has a unique id e.g. in virtual scrolling.
Default behavior with numeric indexes is preserved. With non-numeric indexes, a new prop allItemIndexes is required in order to find the appropriate next/previous item when navigating with the keyboard.
The default behavior when removing the last item from the list if it has focus is different with numeric and non-numeric. With non-numeric it will jump to the beginning of the list instead of the next last item. For more complex behaviors, setNextFocus is overwritable, allowing different focusing behavior when something is removed from the list.

feat(list): Non numeric item indexes

---

.github/workflows/deploy-documentation.yml
.github/workflows/deploy-package.yml
.github/workflows/pull-request.yml

update github actions
- ubuntu 20.04 -> latest - [Will be deprecated in 2025.04.01.](https://github.com/actions/runner-images/issues/11101)
- action/cache v2 -> v4 - [Deprecated in 2025.03.01](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down)

ci: update github workflow

---

src/components/TooltipPopoverCombo/TooltipPopoverCombo.tsx
src/components/TooltipPopoverCombo/TooltipPopoverCombo.unit.test.tsx

Passing the result of the custom (popover and tooltip) onShow result to tippy as expected.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-623004

fix: use result of onShow callback in TooltipPopoverCombo

---

package.json
yarn.lock

- Bumping momentum-design to latest version to get fix for icon a11y issue (not setting role="img" when setting aria-labelledby)
https://github.com/momentum-design/momentum-design/pull/1152

fix: bump-momentum-design-fix-icon-a11y-issue

---

src/components/NotificationSystem/NotificationSystem.style.scss

When passing in a text content to the Notification, the Font was not set correctly, since toastify was setting it to sans-serif.
This is not an issue if toast content is passed in using the Text component, but there are cases where the Text component is not used. This will fix it.

fix: notificationsystem-font-issue

---

package.json
src/components/Coachmark/Coachmark.stories.tsx
src/components/Coachmark/Coachmark.types.ts
yarn.lock

feat(coachmark): pass through event callbacks

---

src/components/NotificationSystem/NotificationSystem.utils.test.tsx
src/components/NotificationSystem/NotificationSystem.utils.ts
src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.tsx
src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.types.ts
src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.unit.test.tsx
src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.unit.test.tsx.snap

- Add isRegistered function to ScreenReaderAnnouncer
- NotificationSystem falls back to its default announcer if announcerIdentity isn't registered, with a warning, to avoid losing notifications to timing issues.
jira: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-635490
original momentum PR: https://github.com/momentum-design/momentum-react-v2/pull/773
accompanying cantina PR: https://sqbu-github.cisco.com/WebExSquared/webex-web-client/pull/7881

fix(device notifications): fall back to default announcer if announcerIdentity not registered

---

src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/Checkbox.unit.test.tsx
src/components/Checkbox/Checkbox.unit.test.tsx.snap
src/components/RadioGroup/Radio.tsx
src/components/RadioGroup/RadioGroup.unit.test.tsx
src/components/RadioGroup/RadioGroup.unit.test.tsx.snap

Update CheckboxNext and Radio to use the aria-label provided instead of always using the label

fix: use aria-label for checkbox/radio if defined instead of label

---

src/components/Toggle/Toggle.types.ts

Add AriaLabelRequired to <Toggle /> since react-aria/toggle complains that it is required.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-591688

fix(Toggle): add AriaLabelRequired

---

src/components/GlobalSearchInput/GlobalSearchInput.style.scss
src/components/SearchInput/SearchInput.style.scss
src/components/TextInput/TextInput.style.scss

- Focus ring was not showing up correctly in inputs after merging AddReactionButton migration PR: https://github.com/momentum-design/momentum-react-v2/pull/779

fix: focus ring issue in inputs

---

src/components/AriaToolbar/AriaToolbar.stories.tsx
src/components/AriaToolbarItem/AriaToolbarItem.tsx
src/utils/navigation.test.ts
src/utils/navigation.ts

Aria Toolbar currently does not work with ButtonCircleToggle & ButtonPillToggle, due to mdc-button being used.
To fix that, the following measurements have been taken:
- Added mdc-button to allowed tagnames in navigation.ts util
- Removed useKeyboard react-aria hook and replaced it with normal onKeydown handler to make all types of buttons work (React-Aria buttons and non React-Aria buttons).
- Tested with consuming client if everything still works as expected.

fix: allow mdc-buttons in aria toolbar to work

---

package.json
src/components/ModalContainer/ModalContainer.types.ts
src/components/OverlayAlert/OverlayAlert.types.ts
src/legacy/EventOverlay/index.js
yarn.lock

- Removing react-focus-lock due to not supporting web components
- Replacing it with react-aria/focus

fix: remove react-focus-lock

---

src/components/ButtonCircleToggle/ButtonCircleToggle.stories.args.ts
src/components/ButtonCircleToggle/ButtonCircleToggle.tsx
src/components/ButtonCircleToggle/ButtonCircleToggle.types.ts
src/components/ButtonCircleToggle/ButtonCircleToggle.unit.test.tsx
src/components/ButtonPillToggle/ButtonPillToggle.stories.args.ts
src/components/ButtonPillToggle/ButtonPillToggle.tsx
src/components/ButtonPillToggle/ButtonPillToggle.types.ts
src/components/ButtonPillToggle/ButtonPillToggle.unit.test.tsx

Button toggles, when controlled, were not working properly:
Parents were passing an isSelected and the selected value was still getting changed internally ignoring the isSelected value.

feat(button-toggles): controlled and uncontrolled should work consistently
