.github/workflows/deploy-documentation.yml
.github/workflows/deploy-package.yml

The scope of the changes in this pull request are to improve our deployment of both documentation and package references. This also enables deployment to a non-protected branch for documentation.
[SPARK-293872](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-293872)

refactor(automation): improve deployment pipeline

---

.github/workflows/deploy-documentation.yml

**HOTFIX**
The scope of the changes in this pull request are to fix the file-cleaning that occurs with automated documentation deployment.

fix(automation): documentation cleanup

---

.github/workflows/deploy-documentation.yml

The changes in this PR are a second attempt to fix a documentation publishing issue.

fix(automation): documentation publishing

---

.github/workflows/deploy-documentation.yml

The scope of the changes in this pr is to re-add the file check to prevent edge-case documentation CI fails on PR merge.

docs(automation): add file check

---

src/components/Avatar/index.ts
src/components/index.ts
src/index.js

Export `PresenceType` enum as part of the default exports of the library.

feat(avatar): export PresenceType enum

---

package.json
yarn.lock

**Upgrade momentum-ui/icons-rebrand to the last version**
```
```
*Provide a …

fix(icons): upgrade momentum-ui/icons-rebrand version

---

src/components/DividerDot/DividerDot.constants.ts
src/components/DividerDot/DividerDot.stories.args.ts
src/components/DividerDot/DividerDot.stories.docs.mdx
src/components/DividerDot/DividerDot.stories.tsx
src/components/DividerDot/DividerDot.style.scss
src/components/DividerDot/DividerDot.tsx
src/components/DividerDot/DividerDot.types.ts
src/components/DividerDot/DividerDot.unit.test.tsx
src/components/DividerDot/DividerDot.unit.test.tsx.snap
src/components/DividerDot/index.ts

Divider dot component
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292468

feat: divider dot component

---

src/components/index.ts
src/index.js

Export Divider dot

---

config/storybook/cjs/preview.js
config/storybook/cjs/theme.decorator.jsx
config/storybook/esm/preview.js
config/storybook/esm/theme.decorator.jsx
config/storybook/src/preview.js
config/storybook/src/theme.decorator.jsx
src/components/ThemeProvider/ThemeProvider.stories.args.ts
src/components/ThemeProvider/ThemeProvider.stories.docs.mdx
src/components/ThemeProvider/ThemeProvider.stories.tsx
src/components/ThemeProvider/ThemeProvider.tsx
src/components/ThemeProvider/ThemeProvider.types.ts
src/components/ThemeProvider/ThemeProvider.unit.test.tsx
src/components/ThemeProvider/ThemeProvider.unit.test.tsx.snap

The scope of the changes in this pull request are to add improvements to the theme provider that allow for a better viewing experience within storybook.
[SPARK-296628](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-296628)

Fix/theme provider/style attribute

---

src/components/SpaceListItem/SpaceListItem.style.scss
src/components/SpaceListItem/SpaceListItem.tsx
src/components/SpaceListItem/SpaceListItem.unit.test.tsx
src/components/SpaceListItem/SpaceListItem.unit.test.tsx.snap

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-287037

Spark 287037 dot compact mode

---

src/components/MeetingListItem/MeetingListItem.stories.tsx

Add action to MeetingListItem in storybook.

refactor(meeting-list-item): add action to storybook

---

src/components/List/List.stories.docs.mdx
src/components/List/List.stories.tsx

Added some more documentation and dynamic example for List component.

feat(list): add better docs

---

src/components/List/List.tsx

The scope of the changes in this pull request are to fix the list focus issue in which children are updated within the list.
[SPARK-305639](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-305639)

fix(components/list): focus swap on child change

---

src/components/List/List.tsx

The scope of the changes in this pull request are to revert a fix that causes testing failures in Cantina around space-list-item focus changes.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-305639

fix(components/list): revert focus change fix

---

src/components/ListHeader/ListHeader.stories.tsx
src/components/ListHeader/ListHeader.style.scss
src/components/ListHeader/ListHeader.tsx
src/components/ListHeader/ListHeader.unit.test.tsx.snap
src/components/Menu/Menu.stories.tsx
src/components/MenuSection/MenuSection.tsx
src/components/MenuSection/MenuSection.unit.test.tsx.snap

Small fixes on the Menu and List Header component
- add height of 1 px for ListHeader with no text and outline
- menu section was giving an error if no `title` prop was given to `<Section>` component
[SPARK-306456](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-306456)

feat(menu-section): fix headers

---

package.json
src/components/Card/Card.constants.ts
src/components/Card/Card.stories.args.ts
src/components/Card/Card.stories.docs.mdx
src/components/Card/Card.stories.tsx
src/components/Card/Card.style.scss
src/components/Card/Card.tsx
src/components/Card/Card.types.ts
src/components/Card/Card.unit.test.tsx
src/components/Card/Card.unit.test.tsx.snap
src/components/Card/CardStatus/CardStatus.constants.ts
src/components/Card/CardStatus/CardStatus.style.scss
src/components/Card/CardStatus/CardStatus.tsx
src/components/Card/CardStatus/CardStatus.types.ts
src/components/Card/CardStatus/CardStatus.unit.test.tsx
src/components/Card/CardStatus/CardStatus.unit.test.tsx.snap
src/components/Card/CardStatus/index.ts
src/components/Card/index.ts
src/components/index.ts
src/helpers/cssTokenCheck.js
src/index.js
yarn.lock

The scope of the changes in this pull request are to create the core `<MeetingCardContainer />` component that will be utilized for all upcoming **Meeting Container** components. This component can be later used as the root for `<MeetingListItem />` container once the **Meeting Container** components are generated.
**Note** - The changes in this pull request also allow for localized CSS Variables to be created to help reduce code footprint and improve readability when multiple variations of a component utilize similar values from our design tokens.
[SPARK-313907](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-313907)
[Figma Article](https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=31674%3A56400).

Feat/meeting card container/create

---

package.json
yarn.lock

**Upgrade momentum-ui/icons-rebrand to the last version**
```
```
*Provide a …

fix(icons): upgrade momentum-ui/icons-rebrand-version

---

package.json
src/components/ButtonHyperlink/ButtonHyperlink.style.scss
src/components/ButtonHyperlink/ButtonHyperlink.tsx
src/components/ButtonHyperlink/ButtonHyperlink.types.ts
src/components/ButtonHyperlink/ButtonHyperlink.unit.test.tsx.snap
src/components/InputMessage/InputMessage.style.scss
src/components/InputMessage/InputMessage.tsx
src/components/InputMessage/InputMessage.unit.test.tsx.snap
src/components/SearchInput/SearchInput.unit.test.tsx.snap
src/components/TextInput/TextInput.stories.tsx
src/components/TextInput/TextInput.unit.test.tsx.snap
src/helpers/verifyTypes.ts
src/helpers/verifyTypes.unit.test.tsx
yarn.lock

- fixed input message bugs around text input
- fixed HTML element for button hyperlink

feat(btn-hyper-and-input): bug fixes

---

src/components/SpaceListItem/SpaceListItem.tsx
src/components/SpaceListItem/SpaceListItem.unit.test.tsx
src/components/SpaceListItem/SpaceListItem.unit.test.tsx.snap

fix(icons): updating draft icon

---

src/components/SpaceListItem/SpaceListItem.types.ts

feat(components/Icon): update draft icon

---

src/components/ButtonCircle/ButtonCircle.unit.test.tsx.snap
src/components/ButtonGroup/ButtonGroup.unit.test.tsx.snap
src/components/ButtonPill/ButtonPill.stories.tsx
src/components/ButtonPill/ButtonPill.unit.test.tsx.snap
src/components/ButtonSimple/ButtonSimple.style.scss
src/components/ButtonSimple/ButtonSimple.tsx
src/components/ButtonSimple/ButtonSimple.unit.test.tsx.snap
src/components/Coachmark/Coachmark.unit.test.tsx.snap
src/components/MeetingContainer/MeetingContainer.unit.test.tsx.snap
src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/components/Toast/Toast.unit.test.tsx.snap
src/components/ToastContent/ToastContent.unit.test.tsx.snap

Added text overflow default for button simple.

feat(button-simple): text overflow

---

src/components/MeetingContainer/MeetingContainer.constants.ts
src/components/MeetingContainer/MeetingContainer.stories.tsx
src/components/MeetingContainer/MeetingContainer.style.scss
src/components/MeetingContainer/MeetingContainer.tsx
src/components/MeetingContainer/MeetingContainer.unit.test.tsx.snap

Added some text overflow fixes to MeetingContainer.
[SPARK-330908](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-330908)

feat(meeting-container): add ovetflow fix

---

src/components/Chip/Chip.constants.ts
src/components/Chip/Chip.stories.args.ts
src/components/Chip/Chip.stories.docs.mdx
src/components/Chip/Chip.stories.tsx
src/components/Chip/Chip.style.scss
src/components/Chip/Chip.tsx
src/components/Chip/Chip.types.ts
src/components/Chip/Chip.unit.test.tsx
src/components/Chip/Chip.unit.test.tsx.snap
src/components/Chip/index.ts

Adds the core chips components as described in the figma
Added the chips component with supporting features and tests as shown in the figma 
https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=34401%3A58258

feat(chips): add core chips component 

---

package.json
src/components/TextToast/TextToast.constants.ts
src/components/TextToast/TextToast.stories.args.ts
src/components/TextToast/TextToast.stories.docs.mdx
src/components/TextToast/TextToast.stories.tsx
src/components/TextToast/TextToast.style.scss
src/components/TextToast/TextToast.tsx
src/components/TextToast/TextToast.types.ts
src/components/TextToast/TextToast.unit.test.tsx
src/components/TextToast/TextToast.unit.test.tsx.snap
src/components/TextToast/index.ts
src/components/index.ts
src/index.js
yarn.lock

- Added Text Toast component as defined in the Figma link below. This is a precondition for the TemporaryUnmute toast.
- Updated tokens dependency to get latest tokens
Figma: https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=44750%3A103463

feat: added text-toast component

---

src/components/ModalContainer/ModalContainer.style.scss
src/components/Popover/Popover.stories.tsx

fix(Popover): fix top arrow

---

package.json
src/components/Checkbox/Checkbox.constants.ts
src/components/Checkbox/Checkbox.stories.args.ts
src/components/Checkbox/Checkbox.stories.docs.mdx
src/components/Checkbox/Checkbox.stories.tsx
src/components/Checkbox/Checkbox.style.scss
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/Checkbox.types.ts
src/components/Checkbox/Checkbox.unit.test.tsx
src/components/Checkbox/Checkbox.unit.test.tsx.snap
src/components/Checkbox/index.ts
src/components/ThemeProvider/ThemeProvider.style.scss
src/components/index.ts
src/index.js
yarn.lock

Add the Checkbox component as defined in the Component Library.
[*Links to relevent resources.*](https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web?node-id=40300%3A80462)

feat(checkbox): add checkbox component

---

package.json
src/components/ToastNotification/ToastNotification.constants.ts
src/components/ToastNotification/ToastNotification.stories.args.ts
src/components/ToastNotification/ToastNotification.stories.docs.mdx
src/components/ToastNotification/ToastNotification.stories.tsx
src/components/ToastNotification/ToastNotification.style.scss
src/components/ToastNotification/ToastNotification.tsx
src/components/ToastNotification/ToastNotification.types.ts
src/components/ToastNotification/ToastNotification.unit.test.tsx
src/components/ToastNotification/ToastNotification.unit.test.tsx.snap
src/components/ToastNotification/index.ts
src/components/index.ts
src/index.js
yarn.lock

Adding Notification Toast component to the library as seen in Figma.
https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=36552%3A55990

feat(notification-toast): add notification toast component

---

package.json
yarn.lock

Update tokens to latest version: v0.0.45
https://github.com/momentum-design/tokens/tags
Update icons-rebrand to latest version: v1.38.0
https://www.npmjs.com/package/@momentum-ui/icons-rebrand

feat(updateTokensIcons): update packages

---

src/components/Popover/Popover.types.ts

Added tippy lifecycle methods on our Popover component.

feat(popover): add lifecycle methods

---

package.json
yarn.lock

Update the icons-rebrand version to 1.39.0.
https://www.npmjs.com/package/@momentum-ui/icons-rebrand

feat(check-circle-icon): update icons rebrand package

---

src/components/ListBoxBase/ListBoxBase.unit.test.tsx.snap
src/components/ListBoxItem/ListBoxItem.tsx
src/components/ListBoxItem/ListBoxItem.unit.test.tsx.snap
src/components/ListBoxSection/ListBoxSection.unit.test.tsx.snap
src/components/ListItemBaseSection/ListItemBaseSection.tsx
src/components/ListItemBaseSection/ListItemBaseSection.types.ts
src/components/ListItemBaseSection/ListItemBaseSection.unit.test.tsx
src/components/ListItemBaseSection/ListItemBaseSection.unit.test.tsx.snap
src/components/Select/Select.unit.test.tsx.snap

Added title prop in ListBaseItemSection
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-343196

fix(title): added title in list base item section for tool tip

---

src/components/index.ts
src/index.js

feat(chip): add it to exports

---

src/components/Select/Select.stories.tsx
src/components/Select/Select.style.scss
src/components/Select/Select.tsx
src/components/Select/Select.unit.test.tsx.snap

- Fixed selected state truncation
Before
After
[SPARK-349100](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-349100)

feat(select): fix animation, and selected state truncation

---

config/storybook/generateMain.js
package.json
src/components/NotificationSystem/NotificationSystem.constants.ts
src/components/NotificationSystem/NotificationSystem.stories.args.ts
src/components/NotificationSystem/NotificationSystem.stories.docs.mdx
src/components/NotificationSystem/NotificationSystem.stories.tsx
src/components/NotificationSystem/NotificationSystem.style.scss
src/components/NotificationSystem/NotificationSystem.tsx
src/components/NotificationSystem/NotificationSystem.types.ts
src/components/NotificationSystem/NotificationSystem.unit.test.tsx
src/components/NotificationSystem/NotificationSystem.unit.test.tsx.snap
src/components/NotificationSystem/NotificationSystem.utils.test.tsx
src/components/NotificationSystem/NotificationSystem.utils.ts
src/components/NotificationSystem/NotificationTemplate.style.scss
src/components/NotificationSystem/NotificationTemplate.tsx
src/components/NotificationSystem/index.ts
src/components/index.ts
src/index.js
yarn.lock

- Added NotificationSystem component
- Added utils and exposed them as part of the compound component pattern
- Added unit tests using RTL for better confidence
- Added sample stories for the usage of the NotificationSystem
- NOTE: NotificationTemplate sub-component is not exposed and only used for storybook. Every consumer can create their notification templates on their own and inject them.
[Jira](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-350110)
[Tech breakdown](https://confluence-eng-gpk2.cisco.com/conf/display/WTWC/SPARK-350110+-+Notification+System)

feat(components): added notification-system component

---

src/components/Tab/Tab.types.ts

fix(tab): allow undefined close #291

---

src/components/Popover/Popover.types.ts

fix(popover): allow undefined for setInstance close #293

---

src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/components/Popover/Popover.constants.ts
src/components/Popover/Popover.tsx
src/components/Popover/Popover.types.ts
src/components/Popover/Popover.unit.test.tsx
src/components/Popover/Popover.unit.test.tsx.snap

feat(popover): add strategy prop close #296

---

src/components/index.ts

Fix import source for button circle toggle.

feat(button-circle-toggle-import): fix import source for button circle toggle

---

src/components/ButtonCircle/ButtonCircle.style.scss
src/components/ButtonCircleToggle/ButtonCircleToggle.stories.tsx
src/components/ButtonCircleToggle/ButtonCircleToggle.style.scss

Adding class names to the styling of ButtonCircle and ButtonCircleToggle.

feat(button-styling-fix): add class style names to buttons

---

package.json
src/components/Avatar/Avatar.tsx
src/components/Avatar/Avatar.types.ts
src/components/Avatar/Avatar.unit.test.tsx.snap
yarn.lock

This PR adds the presence types 'Call' and 'onDevice' to the component 'Avatar'.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-356973
Call: https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=4594%3A9499
onDevice: https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=4594%3A9149

fix(avatar): add call and on-device presence types

---

package.json
yarn.lock

The scope of the changes in this pull request is to update the `@momentum-ui/design-tokens` dependency to include new values, explicitly the `toggleButtonAccent` values.
[JIRA](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-368400).

feat(package): update token dependency

---

package.json
yarn.lock

Bumped the animations dependency to latest version (to get new reactions)

refactor: bump animations dependency

---

GETTING_STARTED.md

feat: trigger release

---

src/components/List/List.stories.tsx
src/components/List/List.unit.test.tsx
src/components/ListBoxBase/ListBoxBase.tsx
src/components/ListItemBase/ListItemBase.tsx
src/components/ListItemBase/ListItemBase.utils.test.tsx
src/components/ListItemBase/ListItemBase.utils.tsx
src/components/Menu/Menu.tsx

- fix shift+tab to the first list item
- can open menu inside list item
- add unit tests
- update list story

fix: update list accessibility

---

src/components/OverlayAlert/OverlayAlert.constants.ts
src/components/OverlayAlert/OverlayAlert.stories.args.ts
src/components/OverlayAlert/OverlayAlert.stories.docs.mdx
src/components/OverlayAlert/OverlayAlert.stories.tsx
src/components/OverlayAlert/OverlayAlert.style.scss
src/components/OverlayAlert/OverlayAlert.tsx
src/components/OverlayAlert/OverlayAlert.types.ts
src/components/OverlayAlert/OverlayAlert.unit.test.tsx
src/components/OverlayAlert/OverlayAlert.unit.test.tsx.snap
src/components/OverlayAlert/index.ts

The scope of the changes in this pull request are to add the new `<OverlayAlert />` component. This component is released as an extension of the existing `<Overlay />` component, and allows for a more strict presentation.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-381399

feat(components/overlay-alert): create component

---

config/storybook/cjs/theme.decorator.jsx
config/storybook/esm/theme.decorator.jsx
config/storybook/src/theme.decorator.jsx
src/components/ThemeProvider/ThemeProvider.constants.ts
src/components/ThemeProvider/ThemeProvider.tsx
src/components/ThemeProvider/ThemeProvider.unit.test.tsx
src/components/ThemeProvider/ThemeProvider.unit.test.tsx.snap

The scope of the changes in this pull request are to add the new stable themes to the class list of the theme provider to support migration to automated tokens.

Feat/theme provider/add stable themes

---

package.json
src/hooks/useDynamicJSONImport.ts
yarn.lock

- Changed to the new momentum-design animations
https://www.npmjs.com/package/@momentum-design/animations
https://github.com/momentum-design/momentum-design/tree/main/packages/%40momentum-design/animations

refactor(animations): changed to new momentum-design animations

---

src/components/Reaction/Reaction.constants.ts
src/components/Reaction/Reaction.stories.tsx
src/components/Reaction/Reaction.style.scss
src/components/Reaction/Reaction.tsx
src/components/Reaction/Reaction.types.ts
src/components/Reaction/Reaction.unit.test.tsx
src/components/Reaction/Reaction.unit.test.tsx.snap

Add onComplete event handler for Reaction component.
Fix loading spinner.
Add error glyph.

feat(reaction): add onComplete

---

package.json
src/components/Reaction/Reaction.constants.ts
src/components/Reaction/Reaction.types.ts
src/components/Reaction/Reaction.unit.test.tsx.snap
yarn.lock

- replace - with _
- update to new animations which has _ instead of - in names

feat(reaction): replace - with _

---

src/components/Reaction/Reaction.util.test.ts
src/components/Reaction/Reaction.util.ts
src/components/ReactionPicker/ReactionPicker.stories.tsx

Fix dashes that I missed in prev PR.

fix(reactions): fix dashes

---

src/components/List/List.stories.args.ts
src/components/List/List.tsx
src/components/List/List.types.ts
src/components/List/List.unit.test.tsx
src/components/List/List.unit.test.tsx.snap

feat(list): list role

---

src/components/OverlayAlert/OverlayAlert.constants.ts

feat: version bump 2023-02-24

---

src/components/Popover/Popover.constants.ts

feat: version bump 2023-02-28

---

src/components/AriaToolbar/AriaToolbar.constants.ts
src/components/AriaToolbar/AriaToolbar.stories.args.ts
src/components/AriaToolbar/AriaToolbar.stories.docs.mdx
src/components/AriaToolbar/AriaToolbar.stories.tsx
src/components/AriaToolbar/AriaToolbar.style.scss
src/components/AriaToolbar/AriaToolbar.tsx
src/components/AriaToolbar/AriaToolbar.types.ts
src/components/AriaToolbar/AriaToolbar.unit.test.tsx
src/components/AriaToolbar/AriaToolbar.unit.test.tsx.snap
src/components/AriaToolbar/index.ts
src/components/index.ts
src/index.js

This implements the aria toolbar pattern.
https://www.w3.org/WAI/ARIA/apg/patterns/toolbar/

Aria toolbar component

---

package.json
src/components/Popover/Popover.unit.test.tsx
yarn.lock

chore(): momentum-design version bump

---

README.md

fix(): for triggering release tag

---

package.json
yarn.lock

- Bump momentum design icons to latest version

feat(icons): bump momentum design icons to v0.0.31

---

package.json
yarn.lock

- Bumped momentum icons to latest to fix upper case issues

fix: bump md icons to 38

---

src/components/ListItemBase/ListItemBase.style.scss
src/components/SpaceListItem/SpaceListItem.constants.ts
src/components/SpaceListItem/SpaceListItem.stories.args.ts
src/components/SpaceListItem/SpaceListItem.stories.tsx
src/components/SpaceListItem/SpaceListItem.style.scss
src/components/SpaceListItem/SpaceListItem.tsx
src/components/SpaceListItem/SpaceListItem.types.ts
src/components/SpaceListItem/SpaceListItem.unit.test.tsx
src/components/SpaceListItem/SpaceListItem.unit.test.tsx.snap

In order to address [SPARK-276648](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-276648), a disabled prop needs to be added to SpaceListItem
Figma: https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web-Application?node-id=24511%3A48620&t=TXZO7c3sW85DiRXi-1
Consequent Cantina PR: https://sqbu-github.cisco.com/WebExSquared/webex-web-client/pull/3832

feat(SPARK-276648): implement isDisabled prop to SpaceListItem

---

package.json
yarn.lock

Bump to momentum-design/icons 0.44

feat(momentum-icons): bump to 0.44

---

src/components/SpaceListItem/SpaceListItem.types.ts

Adding title as a prop to the type of SpaceListItemProps

feat(spaceListItem): add title prop

---

src/components/Reaction/Reaction.tsx

Allowing reactions to be passed other props like aria-label for accessibility.

feat(reactions-rest-props): allow reactions to have other props

---

src/components/ThemeProvider/ThemeProvider.style.scss

- adjust Inter font-spacing to match old CiscoSans

feat(inter): add letter spacing

---

package.json
src/components/Slider/Slider.constants.ts
src/components/Slider/Slider.hooks.test.ts
src/components/Slider/Slider.hooks.ts
src/components/Slider/Slider.stories.args.ts
src/components/Slider/Slider.stories.docs.mdx
src/components/Slider/Slider.stories.tsx
src/components/Slider/Slider.style.scss
src/components/Slider/Slider.tsx
src/components/Slider/Slider.types.ts
src/components/Slider/Slider.unit.test.tsx
src/components/Slider/Slider.unit.test.tsx.snap
src/components/Slider/Slider.utils.test.ts
src/components/Slider/Slider.utils.ts
src/components/Slider/Thumb.tsx
src/components/Slider/index.ts
src/components/index.ts
yarn.lock

- Added new slider component (only for horizontal orientation right now since this is what we need atm)
- Added unit tests
- Accessibility comes from React-aria

feat(slider): added new slider component

---

src/components/ButtonCircle/ButtonCircle.style.scss
src/components/ButtonPill/ButtonPill.style.scss

PR to restructure the colorization styling of ButtonPill and ButtonCircle to cover all the variants in Figma.
[*Links to relevent resources.*](https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web-Application-(CiscoSansTT)?type=design&node-id=5905%3A45&mode=design&t=Qlkeh9PQkliCssPz-1)

feat(button-circle-pill-color): refactor css colors circle and pill btn

---

package.json
yarn.lock

- Update to the latest momentum-design icons

feat: update icons to latest

---

package.json
yarn.lock

Simple update of momentum tokens version from 0.36 to 0.42

feat(SPARK-304931): update momentum tokens version

---

package.json
yarn.lock

Bumping momentum-design to get latest tokens

feat(update-momentum-design): bump version to .44

---

src/components/OverlayAlert/OverlayAlert.style.scss

Fix title placement in overlay alert

fix(overlay-alert): fix title padding

---

src/components/Select/Select.constants.ts
src/components/Select/Select.stories.tsx
src/components/Select/Select.style.scss
src/components/Select/Select.tsx
src/components/Select/Select.types.ts
src/components/Select/Select.unit.test.tsx
src/components/Select/Select.unit.test.tsx.snap

- Made use of the new Popover for the Select listbox
- Fixed accessibility issues
- Added new scenarios to the common story
- Added new prop `listboxMaxHeight` to override the height of it

fix(select): fix select a11y issues and more

---

src/components/ContentSeparator/ContentSeparator.style.scss
src/components/ContentSeparator/ContentSeparator.tsx
src/components/ContentSeparator/ContentSeparator.types.ts
src/components/ContentSeparator/ContentSeparator.unit.test.tsx

Added gradient to contentSeparator

---

src/components/NavigationTab/NavigationTab.constants.ts
src/components/NavigationTab/NavigationTab.stories.tsx
src/components/NavigationTab/NavigationTab.style.scss
src/components/NavigationTab/NavigationTab.types.ts
src/components/NavigationTab/NavigationTab.unit.test.tsx.snap

Added size of 40 to navigationTab

---

package.json

The scope of the changes in this pull request are to fix the node engine version between this project and an internal project.

fix(package): version for node to 16 base

---

package.json
yarn.lock

- Pin the momentum-design/icons version to make sure to not have unwanted icon breakages

build(package): pin momentum-design/icons version

---

src/components/ComboBox/ComboBox.constants.ts
src/components/ComboBox/ComboBox.documentation.mdx
src/components/ComboBox/ComboBox.stories.args.ts
src/components/ComboBox/ComboBox.stories.tsx
src/components/ComboBox/ComboBox.style.scss
src/components/ComboBox/ComboBox.tsx
src/components/ComboBox/ComboBox.types.ts
src/components/ComboBox/ComboBox.unit.test.tsx
src/components/ComboBox/ComboBox.unit.test.tsx.snap
src/components/ComboBox/ComboBox.utils.test.ts
src/components/ComboBox/ComboBox.utils.ts

fix(comboBox): component optimization

---

src/components/AriaGroup/AriaGroup.stories.docs.mdx
src/components/AriaGroup/AriaGroup.stories.tsx
src/components/AriaGroup/AriaGroup.tsx
src/components/AriaGroup/AriaGroup.types.ts
src/components/AriaGroup/AriaGroup.unit.test.tsx
src/components/AriaGroup/AriaGroup.unit.test.tsx.snap
src/components/AriaGroup/index.ts
src/components/index.ts
src/index.js

feat(AriaGroup): create new component AriaGroup

---

src/components/Banner/Banner.unit.test.tsx.snap
src/components/Coachmark/Coachmark.unit.test.tsx.snap
src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/components/ModalContainer/ModalContainer.constants.ts
src/components/ModalContainer/ModalContainer.tsx
src/components/ModalContainer/ModalContainer.types.ts
src/components/ModalContainer/ModalContainer.unit.test.tsx
src/components/ModalContainer/ModalContainer.unit.test.tsx.snap
src/components/NotificationSystem/NotificationSystem.unit.test.tsx.snap
src/components/OverlayAlert/OverlayAlert.unit.test.tsx.snap
src/components/Popover/Popover.tsx
src/components/Popover/Popover.unit.test.tsx
src/components/Popover/Popover.unit.test.tsx.snap
src/components/Select/Select.tsx
src/components/Select/Select.unit.test.tsx
src/components/Select/Select.unit.test.tsx.snap
src/components/ToastNotification/ToastNotification.unit.test.tsx.snap

- Added role and aria-modal to ModalContainer
- Added aria-labelledby to ModalConatiner if interactive
- aria-haspopup and id to triggerComponent
[Tech Breakdown](https://confluence-eng-gpk2.cisco.com/conf/display/WTWC/Bucket+Breakdown+-+SPARK-522085+Overlays)
[SPARK-525339](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-525339)

Spark 525339 popover

---

src/components/GlobalSearchInput/GlobalSearchInput.types.ts
src/components/GlobalSearchInput/GlobalSearchInput.unit.test.tsx
src/components/GlobalSearchInput/GlobalSearchInput.unit.test.tsx.snap

The clear button aria label in Global Search input needs to be a required prop as it is an icon button, in order to meet accessibility requirements. 
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-506071

feat(global-search-input): make clear button aria label required

---

src/components/RadioSimple/RadioSimple.constants.ts
src/components/RadioSimple/RadioSimple.stories.args.ts
src/components/RadioSimple/RadioSimple.stories.docs.mdx
src/components/RadioSimple/RadioSimple.stories.tsx
src/components/RadioSimple/RadioSimple.style.scss
src/components/RadioSimple/RadioSimple.tsx
src/components/RadioSimple/RadioSimple.types.ts
src/components/RadioSimple/RadioSimple.unit.test.tsx
src/components/RadioSimple/RadioSimple.unit.test.tsx.snap
src/components/RadioSimple/index.ts
src/components/RadioSimpleGroup/RadioSimpleGroup.constants.ts
src/components/RadioSimpleGroup/RadioSimpleGroup.stories.args.ts
src/components/RadioSimpleGroup/RadioSimpleGroup.stories.docs.mdx
src/components/RadioSimpleGroup/RadioSimpleGroup.stories.tsx
src/components/RadioSimpleGroup/RadioSimpleGroup.style.scss
src/components/RadioSimpleGroup/RadioSimpleGroup.tsx
src/components/RadioSimpleGroup/RadioSimpleGroup.types.ts
src/components/RadioSimpleGroup/RadioSimpleGroup.unit.test.tsx
src/components/RadioSimpleGroup/RadioSimpleGroup.unit.test.tsx.snap
src/components/RadioSimpleGroup/index.ts
src/components/index.ts
src/index.js

feat(RadioSimpleGroup): RadioSimpleGroup and RadioSimple

---

src/components/MenuTrigger/MenuTrigger.tsx
src/components/MenuTrigger/MenuTrigger.unit.test.tsx
src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/components/Popover/Popover.constants.ts
src/components/Popover/Popover.tsx
src/components/Popover/Popover.types.ts
src/components/Popover/Popover.unit.test.tsx
src/components/Popover/Popover.unit.test.tsx.snap
src/components/Select/Select.unit.test.tsx.snap
src/components/Tooltip/Tooltip.constants.ts
src/components/Tooltip/Tooltip.stories.args.ts
src/components/Tooltip/Tooltip.stories.docs.mdx
src/components/Tooltip/Tooltip.stories.tsx
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/Tooltip.types.ts
src/components/Tooltip/Tooltip.unit.test.tsx
src/components/Tooltip/Tooltip.unit.test.tsx.snap
src/components/Tooltip/index.tsx

Implement the Tooltip component

feat: add new tooltip component

---

src/components/index.ts
src/index.js

Fix missing Tooltip component exports

fix(tooltip): missing export

---

src/legacy/Lightbox/index.js
src/legacy/Lightbox/tests/index.spec.js
src/legacy/Lightbox/tests/index.spec.js.snap

fix(accessibility): add alt for img

---

scss/components/lightbox/lightbox.scss
src/components/Tooltip/Tooltip.unit.test.tsx.snap
src/legacy/Lightbox/index.js
src/legacy/Lightbox/tests/index.spec.js
src/legacy/Lightbox/tests/index.spec.js.snap

- add theme wrapper for lighbox
- required as part of:
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-503208
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-503209
- fixes focus styling for all components inside

feat(lightbox): add theme wrapper

---

src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/Tooltip.types.ts
src/components/TooltipPopoverCombo/TooltipPopoverCombo.stories.docs.mdx
src/components/TooltipPopoverCombo/TooltipPopoverCombo.stories.tsx
src/components/TooltipPopoverCombo/TooltipPopoverCombo.tsx
src/components/TooltipPopoverCombo/TooltipPopoverCombo.types.ts
src/components/TooltipPopoverCombo/TooltipPopoverCombo.unit.test.tsx
src/components/TooltipPopoverCombo/TooltipPopoverCombo.unit.test.tsx.snap
src/components/TooltipPopoverCombo/index.ts
src/components/index.ts
src/index.js

This creates a component that allows you to have a tooltip and a popover on the same trigger component. The tooltip and popover cannot be open at the same time.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-525737

feat(tooltip-popover-combo): add new component

---

src/components/AddReactionButton/AddReactionButton.unit.test.tsx.snap
src/components/AvatarMeetingsListItem/AvatarMeetingsListItem.unit.test.tsx.snap
src/components/Banner/Banner.unit.test.tsx.snap
src/components/ButtonCircle/ButtonCircle.tsx
src/components/ButtonCircle/ButtonCircle.unit.test.tsx
src/components/ButtonCircle/ButtonCircle.unit.test.tsx.snap
src/components/ButtonCircleToggle/ButtonCircleToggle.unit.test.tsx.snap
src/components/ButtonGroup/ButtonGroup.unit.test.tsx.snap
src/components/ButtonPill/ButtonPill.tsx
src/components/ButtonPill/ButtonPill.unit.test.tsx
src/components/ButtonPill/ButtonPill.unit.test.tsx.snap
src/components/ButtonPillToggle/ButtonPillToggle.unit.test.tsx.snap
src/components/ButtonSimple/ButtonSimple.tsx
src/components/ButtonSimple/ButtonSimple.unit.test.tsx
src/components/ButtonSimple/ButtonSimple.unit.test.tsx.snap
src/components/Chip/Chip.unit.test.tsx.snap
src/components/ComboBox/ComboBox.unit.test.tsx.snap
src/components/MeetingContainer/MeetingContainer.unit.test.tsx.snap
src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/components/OverlayAlert/OverlayAlert.unit.test.tsx.snap
src/components/ReactionBadge/ReactionBadge.unit.test.tsx.snap
src/components/ReactionButton/ReactionButton.unit.test.tsx.snap
src/components/ReactionPicker/ReactionPicker.unit.test.tsx.snap
src/components/Toast/Toast.unit.test.tsx.snap
src/components/ToastContent/ToastContent.unit.test.tsx.snap
src/components/ToastNotification/ToastNotification.unit.test.tsx.snap

- add aria-disabled for shallow disabled
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-367651

feat(button): add aria-disabled for shallow disabled

---

src/components/Toggletip/Toggletip.unit.test.tsx.snap
src/components/TooltipPopoverCombo/TooltipPopoverCombo.stories.tsx
src/components/TooltipPopoverCombo/TooltipPopoverCombo.tsx
src/components/TooltipPopoverCombo/TooltipPopoverCombo.types.ts
src/components/TooltipPopoverCombo/TooltipPopoverCombo.unit.test.tsx
src/components/TooltipPopoverCombo/TooltipPopoverCombo.unit.test.tsx.snap

Make sure the aria-labelledby id matches the id on the button

fix(tooltip-popover-combo): fix id for aria labelled by

---

src/components/TextInput/TextInput.tsx
src/components/TextInput/TextInput.unit.test.tsx
src/components/TextInput/TextInput.unit.test.tsx.snap

Added aria-describedby prop to the TextInput component as a result, it is linked to the message component whenever list of messages are passed on.

fix(TextInput): Added aria-describedby prop

---

src/components/Avatar/Avatar.tsx
src/components/Avatar/Avatar.unit.test.tsx
src/components/Avatar/Avatar.unit.test.tsx.snap
src/components/ListItemBase/ListItemBase.test.tsx
src/components/ListItemBase/ListItemBase.tsx
src/components/Popover/Popover.stories.tsx
src/components/Popover/Popover.unit.test.tsx
src/components/SearchInput/SearchInput.tsx

This fixes the following popover -> listitem interaction issues
1) It was required that a list item be placed within a div before being used in a popover
2) keyboard enter press did not cause the popover to open

fix(listitem): fix list item interaction with popover

---

src/components/OverlayAlert/OverlayAlert.stories.tsx
src/components/OverlayAlert/OverlayAlert.tsx
src/components/OverlayAlert/OverlayAlert.unit.test.tsx
src/components/Popover/Popover.events.ts
src/components/Popover/tippy-plugins/hideOnEscPlugin.test.ts
src/components/Popover/tippy-plugins/hideOnEscPlugin.ts
src/components/RadioGroup/RadioGroup.tsx
src/components/RadioGroup/RadioGroup.unit.test.tsx
src/components/RadioSimpleGroup/RadioSimpleGroup.stories.tsx
src/components/RadioSimpleGroup/RadioSimpleGroup.tsx
src/components/RadioSimpleGroup/RadioSimpleGroup.unit.test.tsx
src/hooks/useShouldCloseOnEsc.test.ts
src/hooks/useShouldCloseOnEsc.ts

lint some files so it doesn't happen in my PR (after merge)

chore: lint some files to sort out my PR

---

src/components/Avatar/Avatar.constants.ts
src/components/Avatar/Avatar.stories.args.tsx
src/components/Avatar/Avatar.stories.tsx
src/components/Avatar/Avatar.style.scss
src/components/Avatar/Avatar.tsx
src/components/Avatar/Avatar.types.ts
src/components/Avatar/Avatar.unit.test.tsx
src/components/Avatar/Avatar.unit.test.tsx.snap
src/components/Avatar/Initials.tsx
src/components/Avatar/Presence.tsx
src/components/AvatarMeetingsListItem/AvatarMeetingsListItem.unit.test.tsx.snap
src/components/Banner/Banner.unit.test.tsx.snap
src/components/Chip/Chip.unit.test.tsx.snap
src/components/MeetingContainer/MeetingContainer.unit.test.tsx.snap
src/components/Popover/Popover.unit.test.tsx
src/components/Toast/Toast.unit.test.tsx.snap
src/components/ToastDetails/ToastDetails.unit.test.tsx.snap

feat(avatar): add accessibility-related attributes

---

src/legacy/Lightbox/index.js
src/legacy/Lightbox/tests/index.spec.js
src/legacy/Lightbox/tests/index.spec.js.snap

fix(lightbox): modify for screen reader

---

src/components/AriaToolbar/AriaToolbar.tsx
src/components/AriaToolbar/AriaToolbar.unit.test.tsx
src/components/AriaToolbar/AriaToolbar.unit.test.tsx.snap

- pass down rest props to aria toolbar container
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-505327

feat(aria-toolbar): pass in rest props downstream

---

src/components/ListHeader/ListHeader.constants.ts
src/components/ListHeader/ListHeader.style.scss
src/components/ListHeader/ListHeader.tsx
src/components/ListHeader/ListHeader.unit.test.tsx
src/components/ListHeader/ListHeader.unit.test.tsx.snap

Removed role=separator from ListHeader as that makes everything under it presentational and SR does not announce it.
Instead added a separator and applied css to it

fix(listheader): added separator

---

src/components/NotificationSystem/NotificationSystem.stories.args.ts
src/components/NotificationSystem/NotificationSystem.stories.tsx
src/components/NotificationSystem/NotificationSystem.tsx
src/components/NotificationSystem/NotificationSystem.types.ts
src/components/NotificationSystem/NotificationSystem.unit.test.tsx
src/components/NotificationSystem/NotificationSystem.unit.test.tsx.snap

- Replaced div with section for NotificationSystem and added required attribute ariaLabel to make sure a11y is always met
- Updated stories and unit tests
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section#technical_summary

fix(a11y): added section to notificationsystem

---

src/components/Toggletip/Toggletip.constants.ts
src/components/Toggletip/Toggletip.stories.docs.mdx
src/components/Toggletip/Toggletip.stories.tsx
src/components/Toggletip/Toggletip.tsx
src/components/Toggletip/Toggletip.unit.test.tsx
src/components/Toggletip/Toggletip.unit.test.tsx.snap

- used interactive popover instead of non-interactive with live aria
- added close button
issue: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-502450

fix: re-factor toggletip

---

src/components/List/List.tsx
src/components/List/List.unit.test.tsx
src/components/List/List.unit.test.tsx.snap

fix(list): add rest param to list component

---

src/components/AddReactionButton/AddReactionButton.tsx
src/components/AriaToolbar/AriaToolbar.unit.test.tsx
src/components/AriaToolbar/AriaToolbar.unit.test.tsx.snap
src/components/ButtonGroup/ButtonGroup.tsx
src/components/ButtonGroup/ButtonGroup.unit.test.tsx
src/components/ButtonGroup/ButtonGroup.unit.test.tsx.snap

- pass rest props on button group
- add forward ref to add reaction button

feat(aria-toolbar): pass down props + forward ref

---

src/components/AriaToolbarItem/AriaToolbarItem.tsx
src/components/AriaToolbarItem/AriaToolbarItem.unit.test.tsx

feat(aria-toolbar-item): pass props to children

---

src/components/Accordion/Accordion.constants.ts
src/components/Accordion/Accordion.stories.args.ts
src/components/Accordion/Accordion.stories.docs.mdx
src/components/Accordion/Accordion.stories.tsx
src/components/Accordion/Accordion.style.scss
src/components/Accordion/Accordion.tsx
src/components/Accordion/Accordion.types.ts
src/components/Accordion/Accordion.unit.test.tsx
src/components/Accordion/Accordion.unit.test.tsx.snap
src/components/Accordion/index.ts
src/components/index.ts
src/index.js

- new component
- complies with WAI ARIA guidelines: https://www.w3.org/WAI/ARIA/apg/patterns/accordion/

feat(accordion): new component

---

src/components/Accordion/Accordion.style.scss
src/components/Accordion/Accordion.tsx
src/components/Accordion/Accordion.types.ts
src/components/Accordion/Accordion.unit.test.tsx
src/components/Accordion/Accordion.unit.test.tsx.snap

feat(accordion): pass props down to header button

---

src/components/ListItemBase/ListItemBase.style.scss
src/components/ListItemBase/ListItemBase.test.tsx
src/components/ListItemBase/ListItemBase.types.ts

fix(listitembase): add height auto option

---

src/components/NotificationSystem/NotificationTemplate.tsx
src/components/ToastNotification/ToastNotification.tsx
src/components/ToastNotification/ToastNotification.types.ts
src/components/ToastNotification/ToastNotification.unit.test.tsx
src/components/ToastNotification/ToastNotification.unit.test.tsx.snap

Added ability to pass ariaLabel to ToastNotification.

fix(notifications): added ariaLabel to toast

---

src/components/List/List.constants.ts
src/components/List/List.stories.tsx
src/components/List/List.tsx
src/components/List/List.types.ts
src/components/List/List.unit.test.tsx
src/components/List/List.utils.tsx
src/components/ListItemBase/ListItemBase.test.tsx
src/components/ListItemBase/ListItemBase.tsx
src/components/ListItemBase/ListItemBase.utils.test.tsx
src/components/ListItemBase/ListItemBase.utils.tsx

Align the list keyboard navigation with the other complex components, like Tree and Grid.
This navigation patter match with the native clients behavior
List navigation:
- Up/Down - Select List item in vertical lists
- Left/Right - Select List item in horizontal lists
- Tab - Select the first interactive element of the selected list item
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-548670

feat: rollback list navigation

---

src/components/Avatar/Avatar.tsx
src/components/Avatar/Avatar.unit.test.tsx
src/components/Avatar/Avatar.unit.test.tsx.snap
src/components/AvatarMeetingsListItem/AvatarMeetingsListItem.unit.test.tsx.snap
src/components/Banner/Banner.unit.test.tsx.snap
src/components/Chip/Chip.unit.test.tsx.snap
src/components/MeetingContainer/MeetingContainer.unit.test.tsx.snap
src/components/Toast/Toast.unit.test.tsx.snap
src/components/ToastDetails/ToastDetails.unit.test.tsx.snap

fix(avatar): fix role for avatar container

---

src/components/ButtonSimple/ButtonSimple.tsx
src/components/ButtonSimple/ButtonSimple.unit.test.tsx

fix(ButtonSimple): add aria selected support

---

src/components/ButtonCircleLink/ButtonCircleLink.constants.ts
src/components/ButtonCircleLink/ButtonCircleLink.stories.args.ts
src/components/ButtonCircleLink/ButtonCircleLink.stories.docs.mdx
src/components/ButtonCircleLink/ButtonCircleLink.stories.tsx
src/components/ButtonCircleLink/ButtonCircleLink.style.scss
src/components/ButtonCircleLink/ButtonCircleLink.tsx
src/components/ButtonCircleLink/ButtonCircleLink.types.ts
src/components/ButtonCircleLink/ButtonCircleLink.unit.test.tsx
src/components/ButtonCircleLink/ButtonCircleLink.unit.test.tsx.snap
src/components/ButtonCircleLink/index.ts
src/components/ButtonPillLink/ButtonPillLink.constants.ts
src/components/ButtonPillLink/ButtonPillLink.stories.args.ts
src/components/ButtonPillLink/ButtonPillLink.stories.docs.mdx
src/components/ButtonPillLink/ButtonPillLink.stories.tsx
src/components/ButtonPillLink/ButtonPillLink.style.scss
src/components/ButtonPillLink/ButtonPillLink.tsx
src/components/ButtonPillLink/ButtonPillLink.types.ts
src/components/ButtonPillLink/ButtonPillLink.unit.test.tsx
src/components/ButtonPillLink/ButtonPillLink.unit.test.tsx.snap
src/components/ButtonPillLink/index.ts
src/components/index.ts
src/index.js

#screenshot
- add ButtonCircleLink component
- add ButtonPillLink component
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-549991
https://github.com/momentum-design/momentum-react-v2/pull/549#discussion_r1691249316

feat: add ButtonCircleLink and ButtonPillLink

---

src/components/Menu/Menu.constants.ts
src/components/Menu/Menu.stories.tsx
src/components/Menu/Menu.tsx
src/components/Menu/Menu.types.ts
src/components/Menu/Menu.unit.test.tsx
src/components/MenuTrigger/MenuTrigger.tsx
src/components/MenuTrigger/MenuTrigger.types.ts
src/components/MenuTrigger/MenuTrigger.unit.test.tsx

- Added new prop to Menu component isGroupRole for conditionally adding role="group"
- Added new prop to MenuTrigger component so that role is not defaulted to dialog.

feat(Ally): Added new props to Menu and MenuTrigger components

---

src/components/Menu/Menu.stories.args.ts
src/components/Menu/Menu.tsx
src/components/Menu/Menu.types.ts
src/components/Menu/Menu.unit.test.tsx

Added new prop 'aria-labelledby' prop to Menu component as it is essential to link Menu header with its items
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-505129)

feat(menu): added aria-labelledby prop to Menu component

---

src/components/Avatar/Avatar.tsx
src/components/Avatar/Avatar.unit.test.tsx
src/components/Avatar/Avatar.unit.test.tsx.snap
src/components/Avatar/Presence.tsx
src/components/AvatarMeetingsListItem/AvatarMeetingsListItem.unit.test.tsx.snap
src/components/Banner/Banner.unit.test.tsx.snap
src/components/Chip/Chip.unit.test.tsx.snap
src/components/MeetingContainer/MeetingContainer.unit.test.tsx.snap
src/components/Toast/Toast.unit.test.tsx.snap
src/components/ToastDetails/ToastDetails.unit.test.tsx.snap

fix(avatar): remove role when onPress is passed

---

src/components/List/List.tsx
src/components/Menu/Menu.tsx
src/components/Menu/Menu.types.ts
src/components/Menu/Menu.unit.test.tsx
src/components/Menu/Menu.unit.test.tsx.snap
src/components/MenuItem/MenuItem.tsx
src/components/MenuItem/MenuItem.types.ts
src/components/MenuSection/MenuSection.tsx
src/components/MenuSection/MenuSection.types.ts
src/components/MenuSection/MenuSection.unit.test.tsx.snap
src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/hooks/useOrientationBasedKeyboardNavigation.test.ts
src/hooks/useOrientationBasedKeyboardNavigation.ts

fix(Menu): horizontal keyboard navigation handling

---

css/momentum-ui.css
src/components/Checkbox/Checkbox.style.scss
src/components/ContentSeparator/ContentSeparator.stories.tsx
src/components/ContentSeparator/ContentSeparator.style.scss
src/components/MenuListBackground/MenuListBackground.style.scss
src/components/MenuListBackground/MenuListBackground.tsx
src/components/Select/Select.style.scss
src/components/Toggle/Toggle.style.scss

- fixes some more bugs we found in yesterday's bug bash

feat(token-migration): additional fixes

---

src/components/ThemeProvider/ThemeProvider.style.scss

- fixes scroll bar colour issue

fix(scrollbar): fix token

---

src/components/CodeInput/CodeInput.stories.tsx
src/components/CodeInput/CodeInput.tsx
src/components/CodeInput/CodeInput.types.ts
src/components/CodeInput/CodeInput.unit.test.tsx

fix(codeinput): optionally clear input after done

---

src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.constants.ts
src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.stories.args.ts
src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.stories.docs.mdx
src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.stories.tsx
src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.tsx
src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.types.ts
src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.unit.test.tsx
src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.unit.test.tsx.snap
src/components/ScreenReaderAnnouncer/index.ts
src/components/index.ts
src/index.js

Moving SR Announcer from Cantina to MRV2 for other components in Cantina to reuse it. This component causes a screen reader to announce a message when required.

feat(sr-announcer): move sr announcer from cantina to mrv2

---

src/components/List/List.stories.tsx
src/components/List/List.tsx
src/components/List/List.types.ts
src/components/List/List.unit.test.tsx
src/components/List/List.unit.test.tsx.snap
src/components/List/index.ts
src/components/ListItemBase/ListItemBase.test.tsx
src/components/ListItemBase/ListItemBase.tsx
src/components/index.ts
src/hooks/useOrientationBasedKeyboardNavigation.ts
src/index.js

- add programmatic focus to list

feat(list-next): add programmatic focus

---

src/components/Toggletip/Toggletip.stories.tsx
src/components/Toggletip/Toggletip.tsx
src/components/Toggletip/Toggletip.unit.test.tsx
src/components/Toggletip/Toggletip.unit.test.tsx.snap

As per the toggletip pattern, toggletips should make sr announce its content when the open. 
Source: https://inclusive-components.design/tooltips-toggletips/
So Ive used SRAnnouncement component to do it. 

feat(toggle-announcement): add sr announcement to togglegtip

---

src/components/Tree/Tree.stories.tsx
src/components/Tree/Tree.test.tsx
src/components/Tree/Tree.tsx
src/components/Tree/Tree.types.ts
src/components/TreeNodeBase/TreeNodeBase.constants.ts
src/components/TreeNodeBase/TreeNodeBase.stories.docs.mdx
src/components/TreeNodeBase/TreeNodeBase.stories.tsx
src/components/TreeNodeBase/TreeNodeBase.style.scss
src/components/TreeNodeBase/TreeNodeBase.test.tsx
src/components/TreeNodeBase/TreeNodeBase.test.tsx.snap
src/components/TreeNodeBase/TreeNodeBase.tsx
src/components/TreeNodeBase/TreeNodeBase.types.ts

- re-calculate internal tree when tree structure change
- do not render TreeNodeBase content when the node details are not available

feat: handle dynamic changes in tree component

---

package.json
yarn.lock

Revert "fix(deps): upgrade react-focus-lock"

---

package.json
yarn.lock

trying this again now that the issues with vtree are resolved in cantina.
see https://github.com/momentum-design/momentum-react-v2/pull/611 for details

fix(deps): update focuslock now that ts issues are resolved

---

package.json
yarn.lock

shamefully reverting again to unblock MRV2

Revert "fix(deps): update focuslock now that ts issues are resolved"

---

src/components/GlobalSearchInput/GlobalSearchInput.style.scss
src/components/SearchInput/SearchInput.style.scss
src/components/TextInput/TextInput.style.scss

fix(opactiy): for accessibility

---

src/components/Tree/Tree.stories.tsx
src/components/Tree/Tree.test.tsx
src/components/Tree/Tree.tsx
src/components/TreeNodeBase/TreeNodeBase.style.scss
src/components/TreeNodeBase/TreeNodeBase.test.tsx
src/components/TreeNodeBase/TreeNodeBase.test.tsx.snap
src/components/TreeNodeBase/TreeNodeBase.tsx
src/hooks/useItemSelected.test.ts
src/hooks/useItemSelected.ts

- added selectedItems prop to useItemSelected hook to make it controllable input like component.
- added active-node class to TreeNodeBase

fix: tree component selection

---

src/components/Menu/Menu.stories.args.ts
src/components/Menu/Menu.stories.tsx
src/components/Menu/Menu.tsx
src/components/Menu/Menu.types.ts
src/components/Menu/Menu.unit.test.tsx
src/components/Menu/Menu.utils.test.tsx
src/components/Menu/Menu.utils.ts
src/components/Menu/index.ts
src/components/MenuSelectionGroup/MenuSelectionGroup.constants.ts
src/components/MenuSelectionGroup/MenuSelectionGroup.style.scss
src/components/MenuSelectionGroup/MenuSelectionGroup.tsx
src/components/MenuSelectionGroup/MenuSelectionGroup.types.ts
src/components/MenuSelectionGroup/MenuSelectionGroup.unit.test.tsx
src/components/MenuSelectionGroup/MenuSelectionGroup.unit.test.tsx.snap
src/components/MenuSelectionGroup/index.ts
src/components/index.ts
src/index.js

Adding SelectionGroup for Menu to be able to have +1 sections with different selectionModes. 
Refrence:
https://github.com/adobe/react-spectrum/pull/2091/files#diff-87747db0945a5a01345b500d51e514994436d0b75d18e2e939fc5b41260260d6

feat(selectionGroup): add selection group component

---

src/components/Tree/Tree.test.tsx
src/components/Tree/Tree.tsx
src/components/Tree/Tree.types.ts

new prop, fn, gets called when a node is toggled (open / close)

feat(tree): add on toggle node prop

---

package.json
yarn.lock

fix(icon): bump momentum design icon version

---

src/components/MenuTrigger/MenuTrigger.tsx
src/components/MenuTrigger/MenuTrigger.unit.test.tsx
src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap

Menu shoul dnot have role dialog which it was getting from Popover, now passing role as generic

fix(menutrigger): role to be generic

---

package.json
src/components/Icon/Icon.constants.ts
src/components/Icon/Icon.stories.tsx
src/components/Icon/Icon.tsx
src/components/Icon/Icon.types.ts
src/hooks/useDynamicSVGImport.test.ts
src/hooks/useDynamicSVGImport.ts
yarn.lock

Reverts momentum-design/momentum-react-v2#649

Revert "feat(icon): add brand visuals icons to icon component"

---

src/components/ListItemBase/ListItemBase.style.scss
src/components/SpaceListItem/SpaceListItem.unit.test.tsx.snap
src/components/SpaceRowContent/SpaceRowContent.style.scss
src/components/SpaceRowContent/SpaceRowContent.tsx
src/components/SpaceRowContent/SpaceRowContent.unit.test.tsx.snap
src/components/SpaceTreeNode/SpaceTreeNode.unit.test.tsx.snap
src/components/TreeNodeBase/TreeNodeBase.style.scss

fix(space-row-content): fix text spacing issue of space row content component

---

src/components/TabsProvider/TabsProvider.stories.docs.mdx

fix(tabs-provider): fix very minor typo in docs

---

src/components/TabList/TabList.constants.ts
src/components/TabList/TabList.stories.args.ts
src/components/TabList/TabList.stories.tsx
src/components/TabList/TabList.style.scss
src/components/TabList/TabList.tsx
src/components/TabList/TabList.types.ts
src/components/TabList/TabList.unit.test.tsx
src/components/TabList/TabList.unit.test.tsx.snap

Sometimes tab lists have a background color under them. We want to standarize the application of this background color so that it looks the same everywhere in the app.

feat(tab-list): add hasBackground prop

---

src/components/Toggle/Toggle.style.scss

Adds high contrast styles for Toggle component
| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/47d13aad-20e3-404d-adb5-3e3cc0582146) | ![image](https://github.com/user-attachments/assets/27bd3591-075e-4c2d-8e03-dd4012f3db13) |
Jira: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-576518

fix(Toggle): windows high-contrast - fix styling

---

src/components/ButtonGroup/ButtonGroup.style.scss

fix(rtl): row-reverse for rtl

---

src/components/Menu/Menu.tsx
src/components/Menu/Menu.types.ts
src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
src/components/TabList/TabList.tsx
src/components/TabList/TabList.unit.test.tsx
src/utils/a11y.test.ts
src/utils/a11y.ts

feat(menu): error log message if label is missing

---

src/components/ListBoxItem/ListBoxItem.tsx

fix(lbi): pass size prop through

---

src/components/GlobalSearchInput/GlobalSearchInput.style.scss

fix(global-search-input): input tag text not vertically centered

---

src/components/Icon/Icon.stories.args.ts
src/components/Icon/Icon.stories.tsx
src/components/Icon/Icon.tsx
src/components/Icon/Icon.types.ts
src/components/Icon/Icon.unit.test.tsx
src/components/Icon/Icon.unit.test.tsx.snap

feat(icon): add tooltip-wrapped version

---

src/components/AriaGroup/AriaGroup.stories.tsx
src/components/AriaGroup/AriaGroup.tsx
src/components/AriaGroup/AriaGroup.types.ts
src/components/AriaGroup/AriaGroup.unit.test.tsx
src/components/AriaGroup/AriaGroup.unit.test.tsx.snap

- Add AriaLabelRequired
- Rename props from ariaLabelledBy to aria-labelledby
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-582970

fix(AriaGroup): require aria label

---

src/components/Select/Select.tsx
src/components/Select/Select.types.ts
src/components/Select/Select.unit.test.tsx

Require the Select component to have a label, aria-label or aria-labelledby.
Also renames ariaLabelledBy prop to aria-labelledby.

feat(Select): require label or aria-label or aria-labelledby

---

src/components/Checkbox/Checkbox.constants.ts
src/components/Checkbox/Checkbox.stories.args.ts
src/components/Checkbox/Checkbox.stories.tsx
src/components/Checkbox/Checkbox.style.scss
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/Checkbox.types.ts
src/components/Checkbox/Checkbox.unit.test.tsx
src/components/Checkbox/Checkbox.unit.test.tsx.snap

- Require label, aria-label or aria-labelledby prop (https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-582972)
- Add AriaLabellingProps to Props definition (https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-582968)
- Add description prop and style according to Figma (https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-582968)
Figma Design: https://www.figma.com/design/FmXv8xvun1xAZiOMfztwqg/%F0%9F%A7%A9-Webex-App---Web?m=auto&node-id=40300-80462&t=JBkDsxJT6cWwwE8F-1

feat(Checkbox): add aria labelling props, add accessible name requirement and add description prop

---

src/components/Popover/Popover.style.scss

fix(popover): close button shifts position when focused

---

src/components/NotificationSystem/NotificationSystem.stories.tsx
src/components/NotificationSystem/NotificationSystem.unit.test.tsx
src/components/NotificationSystem/NotificationSystem.unit.test.tsx.snap
src/components/NotificationSystem/NotificationTemplate.tsx
src/components/ToastNotification/ToastNotification.stories.tsx
src/components/ToastNotification/ToastNotification.types.ts
src/components/ToastNotification/ToastNotification.typetest.ts
src/components/ToastNotification/ToastNotification.unit.test.tsx

require close button label where onClose is present in ToastNotification and NotificationTemplate
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-582995

feat(a11y): require close button label where present in ToastNotification and NotificationTemplate

---

src/components/Banner/Banner.types.ts
src/components/Banner/Banner.unit.test.tsx
src/components/Banner/Banner.unit.test.tsx.snap
src/components/ModalContainer/ModalContainer.stories.tsx
src/components/ModalContainer/ModalContainer.types.ts
src/components/ModalContainer/ModalContainer.typetest.ts
src/components/ModalContainer/ModalContainer.unit.test.tsx
src/components/ModalContainer/ModalContainer.unit.test.tsx.snap
src/components/NotificationSystem/NotificationSystem.stories.tsx
src/components/NotificationSystem/NotificationSystem.unit.test.tsx
src/components/NotificationSystem/NotificationSystem.unit.test.tsx.snap
src/components/NotificationSystem/NotificationTemplate.tsx
src/components/NotificationSystem/NotificationTemplate.typetest.ts
src/components/Overlay/Overlay.stories.tsx
src/components/OverlayAlert/OverlayAlert.tsx
src/components/ToastNotification/ToastNotification.stories.tsx
src/components/ToastNotification/ToastNotification.tsx
src/components/ToastNotification/ToastNotification.types.ts
src/components/ToastNotification/ToastNotification.unit.test.tsx
src/components/ToastNotification/ToastNotification.unit.test.tsx.snap

All modal containers should have an aria-label or aria-labelledby that labels them.

feat(ModalContainer): require label

---

package.json
yarn.lock

- Fixed the ellipsis issue in the Text Component by updating momentum-design to latest to bring in the latest fix.
- Verified Fix in Storybook.

fix: ellipsis issue in text

---

src/components/MeetingRowContent/MeetingRowContent.style.scss

css selector used to adjust the content of the meeting list item. But these elements should be modified specifically from the consumer app , if necessary. 
*Links to relevant resources.*
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-600759

fix: meeting list item width problem

---

src/components/List/List.stories.tsx
src/components/List/List.tsx
src/components/List/List.types.ts
src/components/List/List.unit.test.tsx
src/components/ListItemBase/ListItemBase.test.tsx
src/components/ListItemBase/ListItemBase.tsx
src/components/SpaceListItem/SpaceListItem.unit.test.tsx
src/components/TabList/TabList.tsx
src/hooks/useOrientationBasedKeyboardNavigation.test.ts
src/hooks/useOrientationBasedKeyboardNavigation.ts

To improve the performance of the List, remove parts of the context that change often.

feat(list): remove current focus from list item

---

package.json
src/components/ThemeProvider/ThemeProvider.constants.ts
src/components/ThemeProvider/ThemeProvider.tsx
src/components/ThemeProvider/ThemeProvider.unit.test.tsx.snap
yarn.lock

- Bumping tokens repo version to include new themes
- Adding new themes to constants to pass it through to momentum-design
- Tested in Storybook, works as expected (background gradient changing)

fix: adding new themes to themeprovider

---

src/components/VirtualizedList/VirtualizedList.stories.args.ts
src/components/VirtualizedList/VirtualizedList.stories.docs.mdx
src/components/VirtualizedList/VirtualizedList.stories.tsx
src/components/VirtualizedList/VirtualizedList.tsx
src/components/VirtualizedList/VirtualizedList.types.ts
src/components/VirtualizedList/VirtualizedList.unit.test.tsx
src/components/VirtualizedList/index.tsx
src/components/index.ts
src/index.js

feat(VirtualizedList): component and tests added

---

src/components/Chip/Chip.tsx
src/components/Chip/Chip.types.ts
src/components/Chip/Chip.unit.test.tsx.snap

- Adding an option to chip to stoppropagation, to make it work in ListItem

fix: chip stoppropagation

---

package.json
yarn.lock

bump @momentum-design/components version

chore: bump @momentum-design/components version

---

src/components/Reaction/Reaction.types.ts

animation component's type docs

fix: animation component's type docs

---

package.json
src/index.js
yarn.lock

Export Skeleton and Animation from momentum-design/components and update momentum-design/tokens

feat(skeleton): export Skeleton, Animation, and update tokens

---

src/index.js

export Textarea as TextArea from momentum-design
jira link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-672329
momentum-design: https://momentum-design.github.io/momentum-design/storybook-static/index.html?path=/story/components-textarea--example)

feat(TextArea): export Textarea from momentum-design

---

src/components/ThemeProvider/ThemeProvider.constants.ts
src/components/ThemeProvider/ThemeProvider.types.ts

Update theme names to include Webex suffix

fix(theme): update theme names to include Webex suffix

---

package.json
src/components/AlertBanner/AlertBanner.stories.tsx
yarn.lock

bump momentum-design/icons dependency

feat(icon): bump momentum design icon version

---

package.json
yarn.lock

- Bump to latest momentum-design/components to get fixes for Menu and Divider in

fix: bump momentum-design for latest menu fixes

---

src/index.ts

feat(export): re-export the ToggleTip

---

package.json
yarn.lock

- Bump to latest momentum-design version to get fixes in

fix: bump momentum-design for latest fixes

---

README.md

docs: deprecation-notice
